In [ ]:
%load_ext autoreload
%autoreload 1
%aimport computer

In [109]:
c = computer.Computer()
c.load('challenge.bin')
c.run(700000)

Welcome to the Synacor Challenge!
Please record your progress by putting codes like
this one into the challenge website: omOdvXeQsntd

Executing self-test...

self-test complete, all tests pass
The self-test completion code is: MKwBjhCceLVr

== Foothills ==
You find yourself standing at the base of an enormous mountain.  At its base to the north, there is a massive doorway.  A sign nearby reads "Keep out!  Definitely no treasure within!"

Things of in

In [115]:
c = computer.Computer()
c.load('challenge.bin')
c.run()

Welcome to the Synacor Challenge!
Please record your progress by putting codes like
this one into the challenge website: omOdvXeQsntd

Executing self-test...

self-test complete, all tests pass
The self-test completion code is: MKwBjhCceLVr

== Foothills ==
You find yourself standing at the base of an enormous mountain.  At its base to the north, there is a massive doorway.  A sign nearby reads "Keep out!  Definitely no treasure within!"

Things of interest here:
- tablet

There are 2 exits:
- doorway
- south

What do you do?
take tablet


>>> take tablet




Taken.

What do you do?
south


>>> south




== Foothills ==
As you begin to leave, you feel the urge for adventure pulling you back...

There is 1 exit:
- north

What do you do?
north


>>> north




== Foothills ==
You find yourself standing at the base of an enormous mountain.  At its base to the north, there is a massive doorway.  A sign nearby reads "Keep out!  Definitely no treasure within!"

There are 2 exits:
- doorway
- south

What do you do?
doorway


>>> doorway




== Dark cave ==
This seems to be the mouth of a deep cave.  As you peer north into the darkness, you think you hear the echoes of bats deeper within.

There are 2 exits:
- north
- south

What do you do?
north


>>> north




== Dark cave ==
The cave is somewhat narrow here, and the light from the doorway to the south is quite dim.

There are 2 exits:
- north
- south

What do you do?
north


>>> north




== Dark cave ==
The cave acoustics dramatically change as you find yourself at a legde above a large chasm.  There is barely enough light here to notice a rope bridge leading out into the dark emptiness.

There are 2 exits:
- bridge
- south

What do you do?
bridge


>>> bridge




== Rope bridge ==
This rope bridge creaks as you walk along it.  You aren't sure how old it is, or whether it can even support your weight.

There are 2 exits:
- continue
- back

What do you do?
continue


>>> continue




== Falling through the air! ==
As you continue along the bridge, it snaps!  You try to grab the bridge, but it evades your grasp in the darkness.  You are plummeting quickly downward into the chasm...

There is 1 exit:
- down

What do you do?
down


>>> down




== Moss cavern ==
You are standing in a large cavern full of bioluminescent moss.  It must have broken your fall!  The cavern extends to the east and west; at the west end, you think you see a passage leading out of the cavern.

There are 2 exits:
- west
- east

What do you do?
east


>>> east




== Moss cavern ==
You are standing in a large cavern full of bioluminescent moss.  The cavern extends to the west.

Things of interest here:
- empty lantern

There is 1 exit:
- west

What do you do?
take empty lantern


>>> take empty lantern




Taken.

What do you do?
west


>>> west




== Moss cavern ==
You are standing in a large cavern full of bioluminescent moss.  It must have broken your fall!  The cavern extends to the east and west; at the west end, you think you see a passage leading out of the cavern.

There are 2 exits:
- west
- east

What do you do?
west


>>> west




== Moss cavern ==
You are standing in a large cavern full of bioluminescent moss.  The cavern extends to the east.  There is a crevise in the rocks which opens into a passage.

There are 2 exits:
- east
- passage

What do you do?
passage


>>> passage




== Passage ==
You are in a crevise on the west wall of the moss cavern.  A dark passage leads further west.  There is a ladder here which leads down into a smaller, moss-filled cavern below.

There are 3 exits:
- cavern
- ladder
- darkness

What do you do?
ladder


>>> ladder




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




Chiseled on the wall of one of the passageways, you see:

    aiEbrVscqNRb

You take note of this and keep walking.

== Twisty passages ==
You are in a maze of twisty little passages, all alike.

Things of interest here:
- can

There is 1 exit:
- west

What do you do?
can


>>> can




I don't understand; try 'help' for instructions.

What do you do?
take can


>>> take can




Taken.

What do you do?
look can


>>> look can




This can is full of high-quality lantern oil.

What do you do?
use can


>>> use can




You fill your lantern with oil.  It seems to cheer up!


What do you do?
use lantern


>>> use lantern




You light your lantern.

== Twisty passages ==
You are in a maze of twisty little passages, all alike.

There is 1 exit:
- west

What do you do?
look


>>> look




== Twisty passages ==
You are in a maze of twisty little passages, all alike.

There is 1 exit:
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




Chiseled on the wall of one of the passageways, you see:

    aiEbrVscqNRb

You take note of this and keep walking.

== Twisty passages ==
You are in a maze of twisty little passages, all alike.

There is 1 exit:
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




Chiseled on the wall of one of the passageways, you see:

    aiEbrVscqNRb

You take note of this and keep walking.

== Twisty passages ==
You are in a maze of twisty little passages, all alike.

There is 1 exit:
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




Chiseled on the wall of one of the passageways, you see:

    aiEbrVscqNRb

You take note of this and keep walking.

== Twisty passages ==
You are in a maze of twisty little passages, all alike.

There is 1 exit:
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
west


>>> west




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
west


>>> west




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
sout


>>> sout




I don't understand; try 'help' for instructions.

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
west


>>> west




I don't understand; try 'help' for instructions.

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
noth


>>> noth




I don't understand; try 'help' for instructions.

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
west


>>> west




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of alike twisty passages, all little.

There are 3 exits:
- north
- east
- south

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of little twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
north


>>> north




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
east


>>> east




== Twisty passages ==
You are in a maze of alike little passages, all twisty.

The passage to the east looks very dark; you think you hear a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
east


>>> east




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 2 exits:
- north
- south

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty maze of little passages, all alike.

There are 3 exits:
- north
- south
- west

What do you do?
south


>>> south




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a little maze of twisty passages, all alike.

There are 3 exits:
- north
- south
- east

What do you do?
south


>>> south




== Twisty passages ==
You are in a twisty alike of little passages, all maze.

The east passage appears very dark; you feel likely to be eaten by a Grue.

There are 4 exits:
- north
- south
- west
- east

What do you do?
north


>>> north




Chiseled on the wall of one of the passageways, you see:

    aiEbrVscqNRb

You take note of this and keep walking.

== Twisty passages ==
You are in a maze of twisty little passages, all alike.

There is 1 exit:
- west

What do you do?
west


>>> west




== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
inv


>>> inv




Your inventory:
- tablet
- lit lantern

What do you do?
use lit lantern


>>> use lit lantern




You douse your lantern.

== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
use lantern


>>> use lantern




You light your lantern.

== Twisty passages ==
You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.

There are 5 exits:
- ladder
- north
- south
- east
- west

What do you do?
ladder


>>> ladder




== Passage ==
You are in a crevise on the west wall of the moss cavern.  A dark passage leads further west.  There is a ladder here which leads down into a smaller, moss-filled cavern below.

There are 3 exits:
- cavern
- ladder
- darkness

What do you do?
darkness


>>> darkness




== Passage ==
You feel that your light source is more than sufficient to keep grues away.

There are 2 exits:
- continue
- back

What do you do?
continue


>>> continue




== Dark passage ==
You are in a narrow passage.  There is darkness to the west, but you can barely see a glowing opening to the east.

There are 2 exits:
- west
- east

What do you do?
look


>>> look




== Dark passage ==
You are in a narrow passage.  There is darkness to the west, but you can barely see a glowing opening to the east.

There are 2 exits:
- west
- east

What do you do?
west


>>> west




== Dark passage ==
You are in a dark, narrow passage.

There are 2 exits:
- east
- west

What do you do?
east


>>> east




== Dark passage ==
You are in a narrow passage.  There is darkness to the west, but you can barely see a glowing opening to the east.

There are 2 exits:
- west
- east

What do you do?
east


>>> east




== Passage ==
You feel that your light source is more than sufficient to keep grues away.

There are 2 exits:
- continue
- back

What do you do?
continue


>>> continue




== Dark passage ==
You are in a narrow passage.  There is darkness to the west, but you can barely see a glowing opening to the east.

There are 2 exits:
- west
- east

What do you do?
west


>>> west




== Dark passage ==
You are in a dark, narrow passage.

There are 2 exits:
- east
- west

What do you do?
east


>>> east




== Dark passage ==
You are in a narrow passage.  There is darkness to the west, but you can barely see a glowing opening to the east.

There are 2 exits:
- west
- east

What do you do?
west


>>> west




== Dark passage ==
You are in a dark, narrow passage.

There are 2 exits:
- east
- west

What do you do?
west


>>> west




== Dark passage ==
You are in a dark, narrow passage.

There are 2 exits:
- east
- west

What do you do?
west


>>> west




== Dark passage ==
You are in a dark, narrow passage.  To the west, you spot some vegetation where the passage expands.

There are 2 exits:
- east
- west

What do you do?
east


>>> east




== Dark passage ==
You are in a dark, narrow passage.

There are 2 exits:
- east
- west

What do you do?
west


>>> west




== Dark passage ==
You are in a dark, narrow passage.  To the west, you spot some vegetation where the passage expands.

There are 2 exits:
- east
- west

What do you do?
west


>>> west




== Ruins ==
You stand in a large cavern with a huge ruin to the north, overgrown by plant life.  There is a large stone archway to the north acting as the doorway to the ruined complex.  A crevice in the rock to the east leads to an alarmingly dark passageway.

There are 2 exits:
- east
- north

What do you do?
north


>>> north




== Ruins ==
You are in the once-opulent foyer of a massive ruined complex.  There is a door to the south leading to the overgrowth outside and stairs to the north which lead into a larger hall.

Things of interest here:
- red coin

There are 2 exits:
- north
- south

What do you do?
take red coin


>>> take red coin




Taken.

What do you do?
look red coin


>>> look red coin




This coin is made of a red metal.  It has two dots on one side.

What do you do?
look


>>> look




== Ruins ==
You are in the once-opulent foyer of a massive ruined complex.  There is a door to the south leading to the overgrowth outside and stairs to the north which lead into a larger hall.

There are 2 exits:
- north
- south

What do you do?
south


>>> south




== Ruins ==
You stand in a large cavern with a huge ruin to the north, overgrown by plant life.  There is a large stone archway to the north acting as the doorway to the ruined complex.  A crevice in the rock to the east leads to an alarmingly dark passageway.

There are 2 exits:
- east
- north

What do you do?
north


>>> north




== Ruins ==
You are in the once-opulent foyer of a massive ruined complex.  There is a door to the south leading to the overgrowth outside and stairs to the north which lead into a larger hall.

There are 2 exits:
- north
- south

What do you do?
north


>>> north




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
look


>>> look




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
south


>>> south




== Ruins ==
You are in the once-opulent foyer of a massive ruined complex.  There is a door to the south leading to the overgrowth outside and stairs to the north which lead into a larger hall.

There are 2 exits:
- north
- south

What do you do?
north


>>> north




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
west


>>> west




== Ruins ==
You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.

Things of interest here:
- blue coin

There are 2 exits:
- up
- east

What do you do?
take blue coin


>>> take blue coin




Taken.

What do you do?
up


>>> up




== Ruins ==
This was long ago a lavish throne room.  Dried-up fountains and crumbling statues line the walls, and the carved stone throne in the center of the room is falling apart.

Things of interest here:
- shiny coin

There is 1 exit:
- down

What do you do?
take shiny coin


>>> take shiny coin




Taken.

What do you do?
down


>>> down




== Ruins ==
You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.

There are 2 exits:
- up
- east

What do you do?
east


>>> east




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
west


>>> west




== Ruins ==
You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.

There are 2 exits:
- up
- east

What do you do?
east


>>> east




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
east


>>> east




== Ruins ==
You stand in what seems to have once been a dining hall; broken tables and pottery are scattered everywhere.  A staircase here leads down.

Things of interest here:
- concave coin

There are 2 exits:
- down
- west

What do you do?
take concave coin


>>> take concave coin




Taken.

What do you do?
down


>>> down




== Ruins ==
This seems to be a kitchen; there are brick stoves and shelves along the wall.  Everything here has fallen into disrepair.

Things of interest here:
- corroded coin

There is 1 exit:
- up

What do you do?
take corroded coin


>>> take corroded coin




Taken.

What do you do?
up


>>> up




== Ruins ==
You stand in what seems to have once been a dining hall; broken tables and pottery are scattered everywhere.  A staircase here leads down.

There are 2 exits:
- down
- west

What do you do?
west


>>> west




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
look


>>> look




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
inv


>>> inv




Your inventory:
- tablet
- lit lantern
- red coin
- corroded coin
- shiny coin
- concave coin
- blue coin

What do you do?
look red coin


>>> look red coin




This coin is made of a red metal.  It has two dots on one side.

What do you do?
look corroded coin


>>> look corroded coin




This coin is somewhat corroded.  It has a triangle on one side.

What do you do?
look shiny coin


>>> look shiny coin




This coin is somehow still quite shiny.  It has a pentagon on one side.

What do you do?
look blue coin


>>> look blue coin




This coin is made of a blue metal.  It has nine dots on one side.

What do you do?
look concave coin


>>> look concave coin




This coin is slightly rounded, almost like a tiny bowl.  It has seven dots on one side.

What do you do?
look


>>> look




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
use concave coin


>>> use concave coin




You place the concave coin into the leftmost open slot.

What do you do?
look


>>> look




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

7 + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
take concave coin


>>> take concave coin




You see no such item here.

What do you do?
look


>>> look




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

7 + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
look


>>> look




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

7 + _ * _^2 + _^3 - _ = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
use red coin


>>> use red coin




You place the red coin into the leftmost open slot.

What do you do?
use blue coin


>>> use blue coin




You place the blue coin into the leftmost open slot.

What do you do?
use corroded coin


>>> use corroded coin




You place the corroded coin into the leftmost open slot.

What do you do?
use shiny coin


>>> use shiny coin




You place the shiny coin into the leftmost open slot.
As you place the last coin, they are all released onto the floor.

What do you do?
look


>>> look




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

_ + _ * _^2 + _^3 - _ = 399

Things of interest here:
- red coin
- corroded coin
- shiny coin
- concave coin
- blue coin

There are 4 exits:
- north
- south
- east
- west

What do you do?
look red coin


>>> look red coin




This coin is made of a red metal.  It has two dots on one side.

What do you do?
look corroded coin


>>> look corroded coin




This coin is somewhat corroded.  It has a triangle on one side.

What do you do?
look shiny coin


>>> look shiny coin




This coin is somehow still quite shiny.  It has a pentagon on one side.

What do you do?
look concave coin


>>> look concave coin




This coin is slightly rounded, almost like a tiny bowl.  It has seven dots on one side.

What do you do?
look blue coin


>>> look blue coin




This coin is made of a blue metal.  It has nine dots on one side.

What do you do?
use blue coin


>>> use blue coin




You can't find that in your pack.

What do you do?
take blue coin


>>> take blue coin




Taken.

What do you do?
use blue coin


>>> use blue coin




You place the blue coin into the leftmost open slot.

What do you do?
take red coin


>>> take red coin




Taken.

What do you do?
use red coin


>>> use red coin




You place the red coin into the leftmost open slot.

What do you do?
take shiny coin


>>> take shiny coin




Taken.

What do you do?
use shiny coin


>>> use shiny coin




You place the shiny coin into the leftmost open slot.

What do you do?
take concave coin


>>> take concave coin




Taken.

What do you do?
use concave coin


>>> use concave coin




You place the concave coin into the leftmost open slot.

What do you do?
take corroded coin


>>> take corroded coin




Taken.

What do you do?
use corroded coin


>>> use corroded coin




You place the corroded coin into the leftmost open slot.
As you place the last coin, you hear a click from the north door.

What do you do?
look


>>> look




== Ruins ==
You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:

9 + 2 * 5^2 + 7^3 - 3 = 399

There are 4 exits:
- north
- south
- east
- west

What do you do?
north


>>> north




== Ruins ==
Because it has been so well-protected, this room hardly shows signs of decay.  The walls are covered in elaborate murals and decorated with precious metals and stones.

Things of interest here:
- teleporter

There is 1 exit:
- south

What do you do?
look


>>> look




== Ruins ==
Because it has been so well-protected, this room hardly shows signs of decay.  The walls are covered in elaborate murals and decorated with precious metals and stones.

Things of interest here:
- teleporter

There is 1 exit:
- south

What do you do?
take teleporter


>>> take teleporter




Taken.

What do you do?
look


>>> look




== Ruins ==
Because it has been so well-protected, this room hardly shows signs of decay.  The walls are covered in elaborate murals and decorated with precious metals and stones.

There is 1 exit:
- south

What do you do?
use teleporter


>>> use teleporter




You activate the teleporter!  As you spiral through time and space, you think you see a pattern in the stars...

    poCIXNvCICFD

After a few moments, you find yourself back on solid ground and a little disoriented.

== Synacor Headquarters ==
You stand in the lobby of what appears to be a really fun place to work!  Sadly, there doesn't seem to be anyone around at the moment, so you make a note to call them later.  The bookshelf here looks like it might have something interesting in it, though.

Things of interest here:
- business card
- strange book

There is 1 exit:
- outside

What do you do?
look business card


>>> look business card




This business card has "synacor.com" printed in red on one side.

What do you do?
take business card


>>> take business card




Taken.

What do you do?
use business card


>>> use business card




You aren't sure how to use that.

What do you do?
take strange book


>>> take strange book




Taken.

What do you do?
look strange book


>>> look strange book




The cover of this book subtly swirls with colors.  It is titled "A Brief Introduction to Interdimensional Physics".  It reads:

Recent advances in interdimensional physics have produced fascinating
predictions about the fundamentals of our universe!  For example,
interdimensional physics seems to predict that the universe is, at its root, a
purely mathematical construct, and that all events are caused by the
interactions between eight pockets of energy called "registers".
Furthermore, it seems that while the lower registers primarily control mundane
things like sound and light, the highest register (the so-called "eighth
register") is used to control interdimensional events such as teleportation.

A hypothetical such teleportation device would need to have have exactly two
destinations.  One destination would be used when the eighth register is at its
minimum energy level - this would be the default operation assuming the user
has no way to control the eighth register.  In this situa

>>> look




== Synacor Headquarters ==
You stand in the lobby of what appears to be a really fun place to work!  Sadly, there doesn't seem to be anyone around at the moment, so you make a note to call them later.  The bookshelf here looks like it might have something interesting in it, though.

There is 1 exit:
- outside

What do you do?
go outside


>>> go outside




== Synacor Headquarters ==
It's a warm, sunny day!  While the breeze from Lake Erie is certainly refreshing, you don't see anything here that will help you with your quest.

There is 1 exit:
- inside

What do you do?
look


>>> look




== Synacor Headquarters ==
It's a warm, sunny day!  While the breeze from Lake Erie is certainly refreshing, you don't see anything here that will help you with your quest.

There is 1 exit:
- inside

What do you do?
go inside


>>> go inside




== Synacor Headquarters ==
You stand in the lobby of what appears to be a really fun place to work!  Sadly, there doesn't seem to be anyone around at the moment, so you make a note to call them later.  The bookshelf here looks like it might have something interesting in it, though.

There is 1 exit:
- outside

What do you do?
inv


>>> inv




Your inventory:
- tablet
- lit lantern
- teleporter
- business card
- strange book

What do you do?
look strange book


>>> look strange book




The cover of this book subtly swirls with colors.  It is titled "A Brief Introduction to Interdimensional Physics".  It reads:

Recent advances in interdimensional physics have produced fascinating
predictions about the fundamentals of our universe!  For example,
interdimensional physics seems to predict that the universe is, at its root, a
purely mathematical construct, and that all events are caused by the
interactions between eight pockets of energy called "registers".
Furthermore, it seems that while the lower registers primarily control mundane
things like sound and light, the highest register (the so-called "eighth
register") is used to control interdimensional events such as teleportation.

A hypothetical such teleportation device would need to have have exactly two
destinations.  One destination would be used when the eighth register is at its
minimum energy level - this would be the default operation assuming the user
has no way to control the eighth register.  In this situa

KeyboardInterrupt: 

In [143]:
c = computer.Computer()
c.load('challenge.bin')
with open('input.txt') as inp_file:
    c.run(istream=inp_file)

Welcome to the Synacor Challenge!


Step 35: Output flushed


Please record your progress by putting codes like


Step 85: Output flushed


this one into the challenge website: omOdvXeQsntd


Step 135: Output flushed


Step 136: Output flushed


Executing self-test...


Step 159: Output flushed


Step 160: Output flushed
Step 180: Getting R7 = 0


self-test complete, all tests pass


Step 696201: Output flushed


The self-test completion code is: MKwBjhCceLVr


Step 697308: Output flushed


Step 697331: Output flushed


== Foothills ==


Step 697497: Output flushed


You find yourself standing at the base of an enormous mountain.  At its base to the north, there is a massive doorway.  A sign nearby reads "Keep out!  Definitely no treasure within!"


Step 699359: Output flushed


Step 699715: Output flushed


Things of interest here:


Step 700290: Output flushed


- tablet


Step 700423: Output flushed


Step 700672: Output flushed


There are 2 exits:


Step 700744: Output flushed


- doorway


Step 700862: Output flushed


- south


Step 700948: Output flushed


Step 701001: Output flushed


What do you do?


Step 701369: Output flushed
Step 701400: Input
>>> take tablet


Step 701511: Output flushed


Step 701512: Output flushed


Taken.


Step 702358: Output flushed


Step 702424: Output flushed


What do you do?


Step 702792: Output flushed
Step 702823: Input
>>> use tablet


Step 702925: Output flushed


Step 702926: Output flushed


You find yourself writing "SDejwHYBcpaR" on the tablet.  Perhaps it's some kind of code?


Step 706049: Output flushed


Step 706072: Output flushed


Step 706142: Output flushed


What do you do?


Step 706510: Output flushed
Step 706541: Input
>>> doorway


Step 706616: Output flushed


Step 706617: Output flushed


== Dark cave ==


Step 707367: Output flushed


This seems to be the mouth of a deep cave.  As you peer north into the darkness, you think you hear the echoes of bats deeper within.


Step 708729: Output flushed


Step 709056: Output flushed


There are 2 exits:


Step 709128: Output flushed


- north


Step 709226: Output flushed


- south


Step 709312: Output flushed


Step 709365: Output flushed


What do you do?


Step 709733: Output flushed
Step 709764: Input
>>> north


Step 709821: Output flushed


Step 709822: Output flushed


== Dark cave ==


Step 710518: Output flushed


The cave is somewhat narrow here, and the light from the doorway to the south is quite dim.


Step 711460: Output flushed


Step 711787: Output flushed


There are 2 exits:


Step 711859: Output flushed


- north


Step 711957: Output flushed


- south


Step 712043: Output flushed


Step 712096: Output flushed


What do you do?


Step 712464: Output flushed
Step 712495: Input
>>> north


Step 712552: Output flushed


Step 712553: Output flushed


== Dark cave ==


Step 713249: Output flushed


The cave acoustics dramatically change as you find yourself at a legde above a large chasm.  There is barely enough light here to notice a rope bridge leading out into the dark emptiness.


Step 715151: Output flushed


Step 715478: Output flushed


There are 2 exits:


Step 715550: Output flushed


- bridge


Step 715658: Output flushed


- south


Step 715744: Output flushed


Step 715797: Output flushed


What do you do?


Step 716165: Output flushed
Step 716196: Input
>>> bridge


Step 716262: Output flushed


Step 716263: Output flushed


== Rope bridge ==


Step 717006: Output flushed


This rope bridge creaks as you walk along it.  You aren't sure how old it is, or whether it can even support your weight.


Step 718248: Output flushed


Step 718575: Output flushed


There are 2 exits:


Step 718647: Output flushed


- continue


Step 718775: Output flushed


- back


Step 718851: Output flushed


Step 718904: Output flushed


What do you do?


Step 719272: Output flushed
Step 719303: Input
>>> continue


Step 719387: Output flushed


Step 719388: Output flushed


== Falling through the air! ==


Step 720315: Output flushed


As you continue along the bridge, it snaps!  You try to grab the bridge, but it evades your grasp in the darkness.  You are plummeting quickly downward into the chasm...


Step 722037: Output flushed


Step 722364: Output flushed


There is 1 exit:


Step 722429: Output flushed


- down


Step 722517: Output flushed


Step 722570: Output flushed


What do you do?


Step 722938: Output flushed
Step 722969: Input
>>> down


Step 723017: Output flushed


Step 723018: Output flushed


== Moss cavern ==


Step 723879: Output flushed


You are standing in a large cavern full of bioluminescent moss.  It must have broken your fall!  The cavern extends to the east and west; at the west end, you think you see a passage leading out of the cavern.


Step 726001: Output flushed


Step 726328: Output flushed


There are 2 exits:


Step 726400: Output flushed


- west


Step 726488: Output flushed


- east


Step 726564: Output flushed


Step 726617: Output flushed


What do you do?


Step 726985: Output flushed
Step 727016: Input
>>> east


Step 727064: Output flushed


Step 727065: Output flushed


== Moss cavern ==


Step 727977: Output flushed


You are standing in a large cavern full of bioluminescent moss.  The cavern extends to the west.


Step 728969: Output flushed


Step 729325: Output flushed


Things of interest here:


Step 729900: Output flushed


- empty lantern


Step 730118: Output flushed


Step 730352: Output flushed


There is 1 exit:


Step 730417: Output flushed


- west


Step 730505: Output flushed


Step 730558: Output flushed


What do you do?


Step 730926: Output flushed
Step 730957: Input
>>> take empty lantern


Step 731131: Output flushed


Step 731132: Output flushed


Taken.


Step 732120: Output flushed


Step 732186: Output flushed


What do you do?


Step 732554: Output flushed
Step 732585: Input
>>> west


Step 732633: Output flushed


Step 732634: Output flushed


== Moss cavern ==


Step 733479: Output flushed


You are standing in a large cavern full of bioluminescent moss.  It must have broken your fall!  The cavern extends to the east and west; at the west end, you think you see a passage leading out of the cavern.


Step 735601: Output flushed


Step 735928: Output flushed


There are 2 exits:


Step 736000: Output flushed


- west


Step 736088: Output flushed


- east


Step 736164: Output flushed


Step 736217: Output flushed


What do you do?


Step 736585: Output flushed
Step 736616: Input
>>> west


Step 736664: Output flushed


Step 736665: Output flushed


== Moss cavern ==


Step 737510: Output flushed


You are standing in a large cavern full of bioluminescent moss.  The cavern extends to the east.  There is a crevise in the rocks which opens into a passage.


Step 739112: Output flushed


Step 739439: Output flushed


There are 2 exits:


Step 739511: Output flushed


- east


Step 739599: Output flushed


- passage


Step 739705: Output flushed


Step 739758: Output flushed


What do you do?


Step 740126: Output flushed
Step 740157: Input
>>> passage


Step 740232: Output flushed


Step 740233: Output flushed


== Passage ==


Step 740991: Output flushed


You are in a crevise on the west wall of the moss cavern.  A dark passage leads further west.  There is a ladder here which leads down into a smaller, moss-filled cavern below.


Step 742783: Output flushed


Step 743110: Output flushed


There are 3 exits:


Step 743186: Output flushed


- cavern


Step 743294: Output flushed


- ladder


Step 743390: Output flushed


- darkness


Step 743506: Output flushed


Step 743559: Output flushed


What do you do?


Step 743927: Output flushed
Step 743958: Input
>>> ladder


Step 744024: Output flushed


Step 744025: Output flushed


== Twisty passages ==


Step 744878: Output flushed


You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.


Step 746140: Output flushed


Step 746467: Output flushed


There are 5 exits:


Step 746551: Output flushed


- ladder


Step 746659: Output flushed


- north


Step 746745: Output flushed


- south


Step 746831: Output flushed


- east


Step 746907: Output flushed


- west


Step 746983: Output flushed


Step 747036: Output flushed


What do you do?


Step 747404: Output flushed
Step 747435: Input
>>> west


Step 747483: Output flushed


Step 747484: Output flushed


== Twisty passages ==


Step 748532: Output flushed


You are in a little maze of twisty passages, all alike.


Step 749114: Output flushed


Step 749441: Output flushed


There are 3 exits:


Step 749517: Output flushed


- north


Step 749615: Output flushed


- south


Step 749701: Output flushed


- east


Step 749777: Output flushed


Step 749830: Output flushed


What do you do?


Step 750198: Output flushed
Step 750229: Input
>>> south


Step 750286: Output flushed


Step 750287: Output flushed


== Twisty passages ==


Step 751122: Output flushed


You are in a twisty alike of little passages, all maze.


Step 751699: Output flushed


Step 751709: Output flushed


The east passage appears very dark; you feel likely to be eaten by a Grue.


Step 752464: Output flushed


Step 752791: Output flushed


There are 4 exits:


Step 752871: Output flushed


- north


Step 752969: Output flushed


- south


Step 753055: Output flushed


- west


Step 753131: Output flushed


- east


Step 753207: Output flushed


Step 753260: Output flushed


What do you do?


Step 753628: Output flushed
Step 753659: Input
>>> north


Step 753716: Output flushed


Step 753717: Output flushed


Chiseled on the wall of one of the passageways, you see:


Step 755612: Output flushed


Step 755635: Output flushed


    aiEbrVscqNRb


Step 756423: Output flushed


Step 756446: Output flushed


You take note of this and keep walking.


Step 757366: Output flushed


Step 757389: Output flushed


== Twisty passages ==


Step 757608: Output flushed


You are in a maze of twisty little passages, all alike.


Step 758190: Output flushed


Step 758546: Output flushed


Things of interest here:


Step 759121: Output flushed


- can


Step 759284: Output flushed


Step 759473: Output flushed


There is 1 exit:


Step 759538: Output flushed


- west


Step 759626: Output flushed


Step 759679: Output flushed


What do you do?


Step 760047: Output flushed
Step 760078: Input
>>> take can


Step 760162: Output flushed


Step 760163: Output flushed


Taken.


Step 761081: Output flushed


Step 761147: Output flushed


What do you do?


Step 761515: Output flushed
Step 761546: Input
>>> use can


Step 761621: Output flushed


Step 761622: Output flushed


You fill your lantern with oil.  It seems to cheer up!


Step 763644: Output flushed


Step 763667: Output flushed


Step 763735: Output flushed


What do you do?


Step 764103: Output flushed
Step 764134: Input
>>> use lantern


Step 764245: Output flushed


Step 764246: Output flushed


You light your lantern.


Step 765554: Output flushed


Step 765577: Output flushed


== Twisty passages ==


Step 765806: Output flushed


You are in a maze of twisty little passages, all alike.


Step 766388: Output flushed


Step 766715: Output flushed


There is 1 exit:


Step 766780: Output flushed


- west


Step 766868: Output flushed


Step 766921: Output flushed


What do you do?


Step 767289: Output flushed
Step 767320: Input
>>> west


Step 767368: Output flushed


Step 767369: Output flushed


== Twisty passages ==


Step 768257: Output flushed


You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.


Step 769519: Output flushed


Step 769846: Output flushed


There are 5 exits:


Step 769930: Output flushed


- ladder


Step 770038: Output flushed


- north


Step 770124: Output flushed


- south


Step 770210: Output flushed


- east


Step 770286: Output flushed


- west


Step 770362: Output flushed


Step 770415: Output flushed


What do you do?


Step 770783: Output flushed
Step 770814: Input
>>> ladder


Step 770880: Output flushed


Step 770881: Output flushed


== Passage ==


Step 771584: Output flushed


You are in a crevise on the west wall of the moss cavern.  A dark passage leads further west.  There is a ladder here which leads down into a smaller, moss-filled cavern below.


Step 773376: Output flushed


Step 773703: Output flushed


There are 3 exits:


Step 773779: Output flushed


- cavern


Step 773887: Output flushed


- ladder


Step 773983: Output flushed


- darkness


Step 774099: Output flushed


Step 774152: Output flushed


What do you do?


Step 774520: Output flushed
Step 774551: Input
>>> darkness


Step 774635: Output flushed


Step 774636: Output flushed


== Passage ==


Step 775449: Output flushed


You feel that your light source is more than sufficient to keep grues away.


Step 776248: Output flushed


Step 776575: Output flushed


There are 2 exits:


Step 776647: Output flushed


- continue


Step 776775: Output flushed


- back


Step 776851: Output flushed


Step 776904: Output flushed


What do you do?


Step 777272: Output flushed
Step 777303: Input
>>> continue


Step 777387: Output flushed


Step 777388: Output flushed


== Dark passage ==


Step 778215: Output flushed


You are in a narrow passage.  There is darkness to the west, but you can barely see a glowing opening to the east.


Step 779387: Output flushed


Step 779714: Output flushed


There are 2 exits:


Step 779786: Output flushed


- west


Step 779874: Output flushed


- east


Step 779950: Output flushed


Step 780003: Output flushed


What do you do?


Step 780371: Output flushed
Step 780402: Input
>>> west


Step 780450: Output flushed


Step 780451: Output flushed


== Dark passage ==


Step 781326: Output flushed


You are in a dark, narrow passage.


Step 781698: Output flushed


Step 782025: Output flushed


There are 2 exits:


Step 782097: Output flushed


- east


Step 782185: Output flushed


- west


Step 782261: Output flushed


Step 782314: Output flushed


What do you do?


Step 782682: Output flushed
Step 782713: Input
>>> west


Step 782761: Output flushed


Step 782762: Output flushed


== Dark passage ==


Step 783704: Output flushed


You are in a dark, narrow passage.


Step 784076: Output flushed


Step 784403: Output flushed


There are 2 exits:


Step 784475: Output flushed


- east


Step 784563: Output flushed


- west


Step 784639: Output flushed


Step 784692: Output flushed


What do you do?


Step 785060: Output flushed
Step 785091: Input
>>> west


Step 785139: Output flushed


Step 785140: Output flushed


== Dark passage ==


Step 786082: Output flushed


You are in a dark, narrow passage.  To the west, you spot some vegetation where the passage expands.


Step 787114: Output flushed


Step 787441: Output flushed


There are 2 exits:


Step 787513: Output flushed


- east


Step 787601: Output flushed


- west


Step 787677: Output flushed


Step 787730: Output flushed


What do you do?


Step 788098: Output flushed
Step 788129: Input
>>> west


Step 788177: Output flushed


Step 788178: Output flushed


== Ruins ==


Step 789030: Output flushed


You stand in a large cavern with a huge ruin to the north, overgrown by plant life.  There is a large stone archway to the north acting as the doorway to the ruined complex.  A crevice in the rock to the east leads to an alarmingly dark passageway.


Step 791542: Output flushed


Step 791869: Output flushed


There are 2 exits:


Step 791941: Output flushed


- east


Step 792029: Output flushed


- north


Step 792115: Output flushed


Step 792168: Output flushed


What do you do?


Step 792536: Output flushed
Step 792567: Input
>>> north


Step 792624: Output flushed


Step 792625: Output flushed


== Ruins ==


Step 793309: Output flushed


You are in the once-opulent foyer of a massive ruined complex.  There is a door to the south leading to the overgrowth outside and stairs to the north which lead into a larger hall.


Step 795151: Output flushed


Step 795507: Output flushed


Things of interest here:


Step 796082: Output flushed


- red coin


Step 796310: Output flushed


Step 796484: Output flushed


There are 2 exits:


Step 796556: Output flushed


- north


Step 796654: Output flushed


- south


Step 796740: Output flushed


Step 796793: Output flushed


What do you do?


Step 797161: Output flushed
Step 797192: Input
>>> take red coin


Step 797321: Output flushed


Step 797322: Output flushed


Taken.


Step 798350: Output flushed


Step 798416: Output flushed


What do you do?


Step 798784: Output flushed
Step 798815: Input
>>> north


Step 798872: Output flushed


Step 798873: Output flushed


== Ruins ==


Step 799529: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 802196: Output flushed


Step 802206: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 802491: Output flushed


Step 802818: Output flushed


There are 4 exits:


Step 802898: Output flushed


- north


Step 802996: Output flushed


- south


Step 803082: Output flushed


- east


Step 803158: Output flushed


- west


Step 803234: Output flushed


Step 803287: Output flushed


What do you do?


Step 803655: Output flushed
Step 803686: Input
>>> west


Step 803734: Output flushed


Step 803735: Output flushed


== Ruins ==


Step 804643: Output flushed


You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.


Step 806465: Output flushed


Step 806821: Output flushed


Things of interest here:


Step 807396: Output flushed


- blue coin


Step 807694: Output flushed


Step 807808: Output flushed


There are 2 exits:


Step 807880: Output flushed


- up


Step 807948: Output flushed


- east


Step 808024: Output flushed


Step 808077: Output flushed


What do you do?


Step 808445: Output flushed
Step 808476: Input
>>> take blue coin


Step 808614: Output flushed


Step 808615: Output flushed


Taken.


Step 809779: Output flushed


Step 809845: Output flushed


What do you do?


Step 810213: Output flushed
Step 810244: Input
>>> up


Step 810274: Output flushed


Step 810275: Output flushed


== Ruins ==


Step 810889: Output flushed


This was long ago a lavish throne room.  Dried-up fountains and crumbling statues line the walls, and the carved stone throne in the center of the room is falling apart.


Step 812611: Output flushed


Step 812967: Output flushed


Things of interest here:


Step 813542: Output flushed


- shiny coin


Step 813820: Output flushed


Step 813964: Output flushed


There is 1 exit:


Step 814029: Output flushed


- down


Step 814117: Output flushed


Step 814170: Output flushed


What do you do?


Step 814538: Output flushed
Step 814569: Input
>>> take shiny coin


Step 814716: Output flushed


Step 814717: Output flushed


Taken.


Step 815837: Output flushed


Step 815903: Output flushed


What do you do?


Step 816271: Output flushed
Step 816302: Input
>>> down


Step 816350: Output flushed


Step 816351: Output flushed


== Ruins ==


Step 817152: Output flushed


You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.


Step 818974: Output flushed


Step 819301: Output flushed


There are 2 exits:


Step 819373: Output flushed


- up


Step 819441: Output flushed


- east


Step 819517: Output flushed


Step 819570: Output flushed


What do you do?


Step 819938: Output flushed
Step 819969: Input
>>> east


Step 820017: Output flushed


Step 820018: Output flushed


== Ruins ==


Step 820831: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 823498: Output flushed


Step 823508: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 823793: Output flushed


Step 824120: Output flushed


There are 4 exits:


Step 824200: Output flushed


- north


Step 824298: Output flushed


- south


Step 824384: Output flushed


- east


Step 824460: Output flushed


- west


Step 824536: Output flushed


Step 824589: Output flushed


What do you do?


Step 824957: Output flushed
Step 824988: Input
>>> east


Step 825036: Output flushed


Step 825037: Output flushed


== Ruins ==


Step 825878: Output flushed


You stand in what seems to have once been a dining hall; broken tables and pottery are scattered everywhere.  A staircase here leads down.


Step 827290: Output flushed


Step 827646: Output flushed


Things of interest here:


Step 828221: Output flushed


- concave coin


Step 828534: Output flushed


Step 828663: Output flushed


There are 2 exits:


Step 828735: Output flushed


- down


Step 828823: Output flushed


- west


Step 828899: Output flushed


Step 828952: Output flushed


What do you do?


Step 829320: Output flushed
Step 829351: Input
>>> take concave coin


Step 829516: Output flushed


Step 829517: Output flushed


Taken.


Step 830699: Output flushed


Step 830765: Output flushed


What do you do?


Step 831133: Output flushed
Step 831164: Input
>>> down


Step 831212: Output flushed


Step 831213: Output flushed


== Ruins ==


Step 832014: Output flushed


This seems to be a kitchen; there are brick stoves and shelves along the wall.  Everything here has fallen into disrepair.


Step 833266: Output flushed


Step 833622: Output flushed


Things of interest here:


Step 834197: Output flushed


- corroded coin


Step 834490: Output flushed


Step 834649: Output flushed


There is 1 exit:


Step 834714: Output flushed


- up


Step 834782: Output flushed


Step 834835: Output flushed


What do you do?


Step 835203: Output flushed
Step 835234: Input
>>> take corroded coin


Step 835408: Output flushed


Step 835409: Output flushed


Taken.


Step 836586: Output flushed


Step 836652: Output flushed


What do you do?


Step 837020: Output flushed
Step 837051: Input
>>> up


Step 837081: Output flushed


Step 837082: Output flushed


== Ruins ==


Step 837696: Output flushed


You stand in what seems to have once been a dining hall; broken tables and pottery are scattered everywhere.  A staircase here leads down.


Step 839108: Output flushed


Step 839435: Output flushed


There are 2 exits:


Step 839507: Output flushed


- down


Step 839595: Output flushed


- west


Step 839671: Output flushed


Step 839724: Output flushed


What do you do?


Step 840092: Output flushed
Step 840123: Input
>>> west


Step 840171: Output flushed


Step 840172: Output flushed


== Ruins ==


Step 841024: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 843691: Output flushed


Step 843701: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 843986: Output flushed


Step 844313: Output flushed


There are 4 exits:


Step 844393: Output flushed


- north


Step 844491: Output flushed


- south


Step 844577: Output flushed


- east


Step 844653: Output flushed


- west


Step 844729: Output flushed


Step 844782: Output flushed


What do you do?


Step 845150: Output flushed
Step 845181: Input
>>> use blue coin


Step 845310: Output flushed


Step 845311: Output flushed


You place the blue coin into the leftmost open slot.


Step 847490: Output flushed


Step 847568: Output flushed


What do you do?


Step 847936: Output flushed
Step 847967: Input
>>> use red coin


Step 848087: Output flushed


Step 848088: Output flushed


You place the red coin into the leftmost open slot.


Step 850121: Output flushed


Step 850199: Output flushed


What do you do?


Step 850567: Output flushed
Step 850598: Input
>>> use shiny coin


Step 850736: Output flushed


Step 850737: Output flushed


You place the shiny coin into the leftmost open slot.


Step 852882: Output flushed


Step 852960: Output flushed


What do you do?


Step 853328: Output flushed
Step 853359: Input
>>> use concave coin


Step 853515: Output flushed


Step 853516: Output flushed


You place the concave coin into the leftmost open slot.


Step 855743: Output flushed


Step 855821: Output flushed


What do you do?


Step 856189: Output flushed
Step 856220: Input
>>> use corroded coin


Step 856385: Output flushed


Step 856386: Output flushed


You place the corroded coin into the leftmost open slot.


Step 858618: Output flushed


As you place the last coin, you hear a click from the north door.


Step 860193: Output flushed


Step 860264: Output flushed


What do you do?


Step 860632: Output flushed
Step 860663: Input
>>> north


Step 860720: Output flushed


Step 860721: Output flushed


== Ruins ==


Step 861387: Output flushed


Because it has been so well-protected, this room hardly shows signs of decay.  The walls are covered in elaborate murals and decorated with precious metals and stones.


Step 863089: Output flushed


Step 863445: Output flushed


Things of interest here:


Step 864020: Output flushed


- teleporter


Step 864343: Output flushed


Step 864442: Output flushed


There is 1 exit:


Step 864507: Output flushed


- south


Step 864605: Output flushed


Step 864658: Output flushed


What do you do?


Step 865026: Output flushed
Step 865057: Input
>>> take teleporter


Step 865204: Output flushed


Step 865205: Output flushed


Taken.


Step 866454: Output flushed


Step 866520: Output flushed


What do you do?


Step 866888: Output flushed
Step 866919: Input
>>> use teleporter


Step 867057: Output flushed


Step 867058: Output flushed
Step 868128: Getting R7 = 0


You activate the teleporter!  As you spiral through time and space, you think you see a pattern in the stars...


Step 870716: Output flushed


Step 870739: Output flushed


    poCIXNvCICFD


Step 871620: Output flushed


Step 871643: Output flushed


After a few moments, you find yourself back on solid ground and a little disoriented.


Step 873621: Output flushed


Step 873644: Output flushed


== Synacor Headquarters ==


Step 873927: Output flushed


You stand in the lobby of what appears to be a really fun place to work!  Sadly, there doesn't seem to be anyone around at the moment, so you make a note to call them later.  The bookshelf here looks like it might have something interesting in it, though.


Step 876509: Output flushed


Step 876866: Output flushed


Things of interest here:


Step 877441: Output flushed


- business card


Step 877809: Output flushed


- strange book


Step 877975: Output flushed


Step 878044: Output flushed


There is 1 exit:


Step 878109: Output flushed


- outside


Step 878227: Output flushed


Step 878280: Output flushed


What do you do?


Step 878648: Output flushed
Step 878679: Input
>>> take strange book


Step 878844: Output flushed


Step 878845: Output flushed


Taken.


Step 880186: Output flushed


Step 880252: Output flushed


What do you do?


Step 880620: Output flushed
Step 880651: Input
>>> look strange book


Step 880816: Output flushed


Step 880817: Output flushed


The cover of this book subtly swirls with colors.  It is titled "A Brief Introduction to Interdimensional Physics".  It reads:


Step 883115: Output flushed


Step 883125: Output flushed


Recent advances in interdimensional physics have produced fascinating


Step 883825: Output flushed


predictions about the fundamentals of our universe!  For example,


Step 884485: Output flushed


interdimensional physics seems to predict that the universe is, at its root, a


Step 885275: Output flushed


purely mathematical construct, and that all events are caused by the


Step 885965: Output flushed


interactions between eight pockets of energy called "registers".


Step 886615: Output flushed


Furthermore, it seems that while the lower registers primarily control mundane


Step 887405: Output flushed


things like sound and light, the highest register (the so-called "eighth


Step 888135: Output flushed


register") is used to control interdimensional events such as teleportation.


Step 888905: Output flushed


Step 888915: Output flushed


A hypothetical such teleportation device would need to have have exactly two


Step 889685: Output flushed


destinations.  One destination would be used when the eighth register is at its


Step 890485: Output flushed


minimum energy level - this would be the default operation assuming the user


Step 891255: Output flushed


has no way to control the eighth register.  In this situation, the teleporter


Step 892035: Output flushed


should send the user to a preconfigured safe location as a default.


Step 892715: Output flushed


Step 892725: Output flushed


The second destination, however, is predicted to require a very specific


Step 893455: Output flushed


energy level in the eighth register.  The teleporter must take great care to


Step 894225: Output flushed


confirm that this energy level is exactly correct before teleporting its user!


Step 895015: Output flushed


If it is even slightly off, the user would (probably) arrive at the correct


Step 895775: Output flushed


location, but would briefly experience anomalies in the fabric of reality


Step 896515: Output flushed


itself - this is, of course, not recommended.  Any teleporter would need to test


Step 897325: Output flushed


the energy level in the eighth register and abort teleportation if it is not


Step 898095: Output flushed


exactly correct.


Step 898265: Output flushed


Step 898275: Output flushed


This required precision implies that the confirmation mechanism would be very


Step 899055: Output flushed


computationally expensive.  While this would likely not be an issue for large-


Step 899845: Output flushed


scale teleporters, a hypothetical hand-held teleporter would take billions of


Step 900625: Output flushed


years to compute the result and confirm that the eighth register is correct.


Step 901395: Output flushed


Step 901405: Output flushed


If you find yourself trapped in an alternate dimension with nothing but a


Step 902145: Output flushed


hand-held teleporter, you will need to extract the confirmation algorithm,


Step 902895: Output flushed


reimplement it on more powerful hardware, and optimize it.  This should, at the


Step 903695: Output flushed


very least, allow you to determine the value of the eighth register which would


Step 904495: Output flushed


have been accepted by the teleporter's confirmation mechanism.


Step 905125: Output flushed


Step 905135: Output flushed


Then, set the eighth register to this value, activate the teleporter, and


Step 905875: Output flushed


bypass the confirmation mechanism.  If the eighth register is set correctly, no


Step 906675: Output flushed


anomalies should be experienced, but beware - if it is set incorrectly, the


Step 907435: Output flushed


now-bypassed confirmation mechanism will not protect you!


Step 908015: Output flushed


Step 908025: Output flushed


Of course, since teleportation is impossible, this is all totally ridiculous.


Step 908810: Output flushed


Step 908860: Output flushed


What do you do?


Step 909228: Output flushed
Step 909259: Input


RuntimeError: Hit EOF!

In [275]:
# Run until the first time we read R7

TELEPORT_STEP = 868128
c = computer.Computer()
c.load('challenge.bin')
with open('input.txt') as inp_file:
    c.run(num_steps=TELEPORT_STEP, istream=inp_file)
c.regs[7] = 1
c.run(num_steps=872060-TELEPORT_STEP, istream=sys.stdin)

Welcome to the Synacor Challenge!


Step 35: Output flushed


Please record your progress by putting codes like


Step 85: Output flushed


this one into the challenge website: omOdvXeQsntd


Step 135: Output flushed


Step 136: Output flushed


Executing self-test...


Step 159: Output flushed


Step 160: Output flushed
Step 180: Getting R7 = 0


self-test complete, all tests pass


Step 696201: Output flushed


The self-test completion code is: MKwBjhCceLVr


Step 697308: Output flushed


Step 697331: Output flushed


== Foothills ==


Step 697497: Output flushed


You find yourself standing at the base of an enormous mountain.  At its base to the north, there is a massive doorway.  A sign nearby reads "Keep out!  Definitely no treasure within!"


Step 699359: Output flushed


Step 699715: Output flushed


Things of interest here:


Step 700290: Output flushed


- tablet


Step 700423: Output flushed


Step 700672: Output flushed


There are 2 exits:


Step 700744: Output flushed


- doorway


Step 700862: Output flushed


- south


Step 700948: Output flushed


Step 701001: Output flushed


What do you do?


Step 701369: Output flushed
Step 701400: Input
>>> take tablet


Step 701511: Output flushed


Step 701512: Output flushed


Taken.


Step 702358: Output flushed


Step 702424: Output flushed


What do you do?


Step 702792: Output flushed
Step 702823: Input
>>> use tablet


Step 702925: Output flushed


Step 702926: Output flushed


You find yourself writing "SDejwHYBcpaR" on the tablet.  Perhaps it's some kind of code?


Step 706049: Output flushed


Step 706072: Output flushed


Step 706142: Output flushed


What do you do?


Step 706510: Output flushed
Step 706541: Input
>>> doorway


Step 706616: Output flushed


Step 706617: Output flushed


== Dark cave ==


Step 707367: Output flushed


This seems to be the mouth of a deep cave.  As you peer north into the darkness, you think you hear the echoes of bats deeper within.


Step 708729: Output flushed


Step 709056: Output flushed


There are 2 exits:


Step 709128: Output flushed


- north


Step 709226: Output flushed


- south


Step 709312: Output flushed


Step 709365: Output flushed


What do you do?


Step 709733: Output flushed
Step 709764: Input
>>> north


Step 709821: Output flushed


Step 709822: Output flushed


== Dark cave ==


Step 710518: Output flushed


The cave is somewhat narrow here, and the light from the doorway to the south is quite dim.


Step 711460: Output flushed


Step 711787: Output flushed


There are 2 exits:


Step 711859: Output flushed


- north


Step 711957: Output flushed


- south


Step 712043: Output flushed


Step 712096: Output flushed


What do you do?


Step 712464: Output flushed
Step 712495: Input
>>> north


Step 712552: Output flushed


Step 712553: Output flushed


== Dark cave ==


Step 713249: Output flushed


The cave acoustics dramatically change as you find yourself at a legde above a large chasm.  There is barely enough light here to notice a rope bridge leading out into the dark emptiness.


Step 715151: Output flushed


Step 715478: Output flushed


There are 2 exits:


Step 715550: Output flushed


- bridge


Step 715658: Output flushed


- south


Step 715744: Output flushed


Step 715797: Output flushed


What do you do?


Step 716165: Output flushed
Step 716196: Input
>>> bridge


Step 716262: Output flushed


Step 716263: Output flushed


== Rope bridge ==


Step 717006: Output flushed


This rope bridge creaks as you walk along it.  You aren't sure how old it is, or whether it can even support your weight.


Step 718248: Output flushed


Step 718575: Output flushed


There are 2 exits:


Step 718647: Output flushed


- continue


Step 718775: Output flushed


- back


Step 718851: Output flushed


Step 718904: Output flushed


What do you do?


Step 719272: Output flushed
Step 719303: Input
>>> continue


Step 719387: Output flushed


Step 719388: Output flushed


== Falling through the air! ==


Step 720315: Output flushed


As you continue along the bridge, it snaps!  You try to grab the bridge, but it evades your grasp in the darkness.  You are plummeting quickly downward into the chasm...


Step 722037: Output flushed


Step 722364: Output flushed


There is 1 exit:


Step 722429: Output flushed


- down


Step 722517: Output flushed


Step 722570: Output flushed


What do you do?


Step 722938: Output flushed
Step 722969: Input
>>> down


Step 723017: Output flushed


Step 723018: Output flushed


== Moss cavern ==


Step 723879: Output flushed


You are standing in a large cavern full of bioluminescent moss.  It must have broken your fall!  The cavern extends to the east and west; at the west end, you think you see a passage leading out of the cavern.


Step 726001: Output flushed


Step 726328: Output flushed


There are 2 exits:


Step 726400: Output flushed


- west


Step 726488: Output flushed


- east


Step 726564: Output flushed


Step 726617: Output flushed


What do you do?


Step 726985: Output flushed
Step 727016: Input
>>> east


Step 727064: Output flushed


Step 727065: Output flushed


== Moss cavern ==


Step 727977: Output flushed


You are standing in a large cavern full of bioluminescent moss.  The cavern extends to the west.


Step 728969: Output flushed


Step 729325: Output flushed


Things of interest here:


Step 729900: Output flushed


- empty lantern


Step 730118: Output flushed


Step 730352: Output flushed


There is 1 exit:


Step 730417: Output flushed


- west


Step 730505: Output flushed


Step 730558: Output flushed


What do you do?


Step 730926: Output flushed
Step 730957: Input
>>> take empty lantern


Step 731131: Output flushed


Step 731132: Output flushed


Taken.


Step 732120: Output flushed


Step 732186: Output flushed


What do you do?


Step 732554: Output flushed
Step 732585: Input
>>> west


Step 732633: Output flushed


Step 732634: Output flushed


== Moss cavern ==


Step 733479: Output flushed


You are standing in a large cavern full of bioluminescent moss.  It must have broken your fall!  The cavern extends to the east and west; at the west end, you think you see a passage leading out of the cavern.


Step 735601: Output flushed


Step 735928: Output flushed


There are 2 exits:


Step 736000: Output flushed


- west


Step 736088: Output flushed


- east


Step 736164: Output flushed


Step 736217: Output flushed


What do you do?


Step 736585: Output flushed
Step 736616: Input
>>> west


Step 736664: Output flushed


Step 736665: Output flushed


== Moss cavern ==


Step 737510: Output flushed


You are standing in a large cavern full of bioluminescent moss.  The cavern extends to the east.  There is a crevise in the rocks which opens into a passage.


Step 739112: Output flushed


Step 739439: Output flushed


There are 2 exits:


Step 739511: Output flushed


- east


Step 739599: Output flushed


- passage


Step 739705: Output flushed


Step 739758: Output flushed


What do you do?


Step 740126: Output flushed
Step 740157: Input
>>> passage


Step 740232: Output flushed


Step 740233: Output flushed


== Passage ==


Step 740991: Output flushed


You are in a crevise on the west wall of the moss cavern.  A dark passage leads further west.  There is a ladder here which leads down into a smaller, moss-filled cavern below.


Step 742783: Output flushed


Step 743110: Output flushed


There are 3 exits:


Step 743186: Output flushed


- cavern


Step 743294: Output flushed


- ladder


Step 743390: Output flushed


- darkness


Step 743506: Output flushed


Step 743559: Output flushed


What do you do?


Step 743927: Output flushed
Step 743958: Input
>>> ladder


Step 744024: Output flushed


Step 744025: Output flushed


== Twisty passages ==


Step 744878: Output flushed


You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.


Step 746140: Output flushed


Step 746467: Output flushed


There are 5 exits:


Step 746551: Output flushed


- ladder


Step 746659: Output flushed


- north


Step 746745: Output flushed


- south


Step 746831: Output flushed


- east


Step 746907: Output flushed


- west


Step 746983: Output flushed


Step 747036: Output flushed


What do you do?


Step 747404: Output flushed
Step 747435: Input
>>> west


Step 747483: Output flushed


Step 747484: Output flushed


== Twisty passages ==


Step 748532: Output flushed


You are in a little maze of twisty passages, all alike.


Step 749114: Output flushed


Step 749441: Output flushed


There are 3 exits:


Step 749517: Output flushed


- north


Step 749615: Output flushed


- south


Step 749701: Output flushed


- east


Step 749777: Output flushed


Step 749830: Output flushed


What do you do?


Step 750198: Output flushed
Step 750229: Input
>>> south


Step 750286: Output flushed


Step 750287: Output flushed


== Twisty passages ==


Step 751122: Output flushed


You are in a twisty alike of little passages, all maze.


Step 751699: Output flushed


Step 751709: Output flushed


The east passage appears very dark; you feel likely to be eaten by a Grue.


Step 752464: Output flushed


Step 752791: Output flushed


There are 4 exits:


Step 752871: Output flushed


- north


Step 752969: Output flushed


- south


Step 753055: Output flushed


- west


Step 753131: Output flushed


- east


Step 753207: Output flushed


Step 753260: Output flushed


What do you do?


Step 753628: Output flushed
Step 753659: Input
>>> north


Step 753716: Output flushed


Step 753717: Output flushed


Chiseled on the wall of one of the passageways, you see:


Step 755612: Output flushed


Step 755635: Output flushed


    aiEbrVscqNRb


Step 756423: Output flushed


Step 756446: Output flushed


You take note of this and keep walking.


Step 757366: Output flushed


Step 757389: Output flushed


== Twisty passages ==


Step 757608: Output flushed


You are in a maze of twisty little passages, all alike.


Step 758190: Output flushed


Step 758546: Output flushed


Things of interest here:


Step 759121: Output flushed


- can


Step 759284: Output flushed


Step 759473: Output flushed


There is 1 exit:


Step 759538: Output flushed


- west


Step 759626: Output flushed


Step 759679: Output flushed


What do you do?


Step 760047: Output flushed
Step 760078: Input
>>> take can


Step 760162: Output flushed


Step 760163: Output flushed


Taken.


Step 761081: Output flushed


Step 761147: Output flushed


What do you do?


Step 761515: Output flushed
Step 761546: Input
>>> use can


Step 761621: Output flushed


Step 761622: Output flushed


You fill your lantern with oil.  It seems to cheer up!


Step 763644: Output flushed


Step 763667: Output flushed


Step 763735: Output flushed


What do you do?


Step 764103: Output flushed
Step 764134: Input
>>> use lantern


Step 764245: Output flushed


Step 764246: Output flushed


You light your lantern.


Step 765554: Output flushed


Step 765577: Output flushed


== Twisty passages ==


Step 765806: Output flushed


You are in a maze of twisty little passages, all alike.


Step 766388: Output flushed


Step 766715: Output flushed


There is 1 exit:


Step 766780: Output flushed


- west


Step 766868: Output flushed


Step 766921: Output flushed


What do you do?


Step 767289: Output flushed
Step 767320: Input
>>> west


Step 767368: Output flushed


Step 767369: Output flushed


== Twisty passages ==


Step 768257: Output flushed


You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.


Step 769519: Output flushed


Step 769846: Output flushed


There are 5 exits:


Step 769930: Output flushed


- ladder


Step 770038: Output flushed


- north


Step 770124: Output flushed


- south


Step 770210: Output flushed


- east


Step 770286: Output flushed


- west


Step 770362: Output flushed


Step 770415: Output flushed


What do you do?


Step 770783: Output flushed
Step 770814: Input
>>> ladder


Step 770880: Output flushed


Step 770881: Output flushed


== Passage ==


Step 771584: Output flushed


You are in a crevise on the west wall of the moss cavern.  A dark passage leads further west.  There is a ladder here which leads down into a smaller, moss-filled cavern below.


Step 773376: Output flushed


Step 773703: Output flushed


There are 3 exits:


Step 773779: Output flushed


- cavern


Step 773887: Output flushed


- ladder


Step 773983: Output flushed


- darkness


Step 774099: Output flushed


Step 774152: Output flushed


What do you do?


Step 774520: Output flushed
Step 774551: Input
>>> darkness


Step 774635: Output flushed


Step 774636: Output flushed


== Passage ==


Step 775449: Output flushed


You feel that your light source is more than sufficient to keep grues away.


Step 776248: Output flushed


Step 776575: Output flushed


There are 2 exits:


Step 776647: Output flushed


- continue


Step 776775: Output flushed


- back


Step 776851: Output flushed


Step 776904: Output flushed


What do you do?


Step 777272: Output flushed
Step 777303: Input
>>> continue


Step 777387: Output flushed


Step 777388: Output flushed


== Dark passage ==


Step 778215: Output flushed


You are in a narrow passage.  There is darkness to the west, but you can barely see a glowing opening to the east.


Step 779387: Output flushed


Step 779714: Output flushed


There are 2 exits:


Step 779786: Output flushed


- west


Step 779874: Output flushed


- east


Step 779950: Output flushed


Step 780003: Output flushed


What do you do?


Step 780371: Output flushed
Step 780402: Input
>>> west


Step 780450: Output flushed


Step 780451: Output flushed


== Dark passage ==


Step 781326: Output flushed


You are in a dark, narrow passage.


Step 781698: Output flushed


Step 782025: Output flushed


There are 2 exits:


Step 782097: Output flushed


- east


Step 782185: Output flushed


- west


Step 782261: Output flushed


Step 782314: Output flushed


What do you do?


Step 782682: Output flushed
Step 782713: Input
>>> west


Step 782761: Output flushed


Step 782762: Output flushed


== Dark passage ==


Step 783704: Output flushed


You are in a dark, narrow passage.


Step 784076: Output flushed


Step 784403: Output flushed


There are 2 exits:


Step 784475: Output flushed


- east


Step 784563: Output flushed


- west


Step 784639: Output flushed


Step 784692: Output flushed


What do you do?


Step 785060: Output flushed
Step 785091: Input
>>> west


Step 785139: Output flushed


Step 785140: Output flushed


== Dark passage ==


Step 786082: Output flushed


You are in a dark, narrow passage.  To the west, you spot some vegetation where the passage expands.


Step 787114: Output flushed


Step 787441: Output flushed


There are 2 exits:


Step 787513: Output flushed


- east


Step 787601: Output flushed


- west


Step 787677: Output flushed


Step 787730: Output flushed


What do you do?


Step 788098: Output flushed
Step 788129: Input
>>> west


Step 788177: Output flushed


Step 788178: Output flushed


== Ruins ==


Step 789030: Output flushed


You stand in a large cavern with a huge ruin to the north, overgrown by plant life.  There is a large stone archway to the north acting as the doorway to the ruined complex.  A crevice in the rock to the east leads to an alarmingly dark passageway.


Step 791542: Output flushed


Step 791869: Output flushed


There are 2 exits:


Step 791941: Output flushed


- east


Step 792029: Output flushed


- north


Step 792115: Output flushed


Step 792168: Output flushed


What do you do?


Step 792536: Output flushed
Step 792567: Input
>>> north


Step 792624: Output flushed


Step 792625: Output flushed


== Ruins ==


Step 793309: Output flushed


You are in the once-opulent foyer of a massive ruined complex.  There is a door to the south leading to the overgrowth outside and stairs to the north which lead into a larger hall.


Step 795151: Output flushed


Step 795507: Output flushed


Things of interest here:


Step 796082: Output flushed


- red coin


Step 796310: Output flushed


Step 796484: Output flushed


There are 2 exits:


Step 796556: Output flushed


- north


Step 796654: Output flushed


- south


Step 796740: Output flushed


Step 796793: Output flushed


What do you do?


Step 797161: Output flushed
Step 797192: Input
>>> take red coin


Step 797321: Output flushed


Step 797322: Output flushed


Taken.


Step 798350: Output flushed


Step 798416: Output flushed


What do you do?


Step 798784: Output flushed
Step 798815: Input
>>> north


Step 798872: Output flushed


Step 798873: Output flushed


== Ruins ==


Step 799529: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 802196: Output flushed


Step 802206: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 802491: Output flushed


Step 802818: Output flushed


There are 4 exits:


Step 802898: Output flushed


- north


Step 802996: Output flushed


- south


Step 803082: Output flushed


- east


Step 803158: Output flushed


- west


Step 803234: Output flushed


Step 803287: Output flushed


What do you do?


Step 803655: Output flushed
Step 803686: Input
>>> west


Step 803734: Output flushed


Step 803735: Output flushed


== Ruins ==


Step 804643: Output flushed


You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.


Step 806465: Output flushed


Step 806821: Output flushed


Things of interest here:


Step 807396: Output flushed


- blue coin


Step 807694: Output flushed


Step 807808: Output flushed


There are 2 exits:


Step 807880: Output flushed


- up


Step 807948: Output flushed


- east


Step 808024: Output flushed


Step 808077: Output flushed


What do you do?


Step 808445: Output flushed
Step 808476: Input
>>> take blue coin


Step 808614: Output flushed


Step 808615: Output flushed


Taken.


Step 809779: Output flushed


Step 809845: Output flushed


What do you do?


Step 810213: Output flushed
Step 810244: Input
>>> up


Step 810274: Output flushed


Step 810275: Output flushed


== Ruins ==


Step 810889: Output flushed


This was long ago a lavish throne room.  Dried-up fountains and crumbling statues line the walls, and the carved stone throne in the center of the room is falling apart.


Step 812611: Output flushed


Step 812967: Output flushed


Things of interest here:


Step 813542: Output flushed


- shiny coin


Step 813820: Output flushed


Step 813964: Output flushed


There is 1 exit:


Step 814029: Output flushed


- down


Step 814117: Output flushed


Step 814170: Output flushed


What do you do?


Step 814538: Output flushed
Step 814569: Input
>>> take shiny coin


Step 814716: Output flushed


Step 814717: Output flushed


Taken.


Step 815837: Output flushed


Step 815903: Output flushed


What do you do?


Step 816271: Output flushed
Step 816302: Input
>>> down


Step 816350: Output flushed


Step 816351: Output flushed


== Ruins ==


Step 817152: Output flushed


You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.


Step 818974: Output flushed


Step 819301: Output flushed


There are 2 exits:


Step 819373: Output flushed


- up


Step 819441: Output flushed


- east


Step 819517: Output flushed


Step 819570: Output flushed


What do you do?


Step 819938: Output flushed
Step 819969: Input
>>> east


Step 820017: Output flushed


Step 820018: Output flushed


== Ruins ==


Step 820831: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 823498: Output flushed


Step 823508: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 823793: Output flushed


Step 824120: Output flushed


There are 4 exits:


Step 824200: Output flushed


- north


Step 824298: Output flushed


- south


Step 824384: Output flushed


- east


Step 824460: Output flushed


- west


Step 824536: Output flushed


Step 824589: Output flushed


What do you do?


Step 824957: Output flushed
Step 824988: Input
>>> east


Step 825036: Output flushed


Step 825037: Output flushed


== Ruins ==


Step 825878: Output flushed


You stand in what seems to have once been a dining hall; broken tables and pottery are scattered everywhere.  A staircase here leads down.


Step 827290: Output flushed


Step 827646: Output flushed


Things of interest here:


Step 828221: Output flushed


- concave coin


Step 828534: Output flushed


Step 828663: Output flushed


There are 2 exits:


Step 828735: Output flushed


- down


Step 828823: Output flushed


- west


Step 828899: Output flushed


Step 828952: Output flushed


What do you do?


Step 829320: Output flushed
Step 829351: Input
>>> take concave coin


Step 829516: Output flushed


Step 829517: Output flushed


Taken.


Step 830699: Output flushed


Step 830765: Output flushed


What do you do?


Step 831133: Output flushed
Step 831164: Input
>>> down


Step 831212: Output flushed


Step 831213: Output flushed


== Ruins ==


Step 832014: Output flushed


This seems to be a kitchen; there are brick stoves and shelves along the wall.  Everything here has fallen into disrepair.


Step 833266: Output flushed


Step 833622: Output flushed


Things of interest here:


Step 834197: Output flushed


- corroded coin


Step 834490: Output flushed


Step 834649: Output flushed


There is 1 exit:


Step 834714: Output flushed


- up


Step 834782: Output flushed


Step 834835: Output flushed


What do you do?


Step 835203: Output flushed
Step 835234: Input
>>> take corroded coin


Step 835408: Output flushed


Step 835409: Output flushed


Taken.


Step 836586: Output flushed


Step 836652: Output flushed


What do you do?


Step 837020: Output flushed
Step 837051: Input
>>> up


Step 837081: Output flushed


Step 837082: Output flushed


== Ruins ==


Step 837696: Output flushed


You stand in what seems to have once been a dining hall; broken tables and pottery are scattered everywhere.  A staircase here leads down.


Step 839108: Output flushed


Step 839435: Output flushed


There are 2 exits:


Step 839507: Output flushed


- down


Step 839595: Output flushed


- west


Step 839671: Output flushed


Step 839724: Output flushed


What do you do?


Step 840092: Output flushed
Step 840123: Input
>>> west


Step 840171: Output flushed


Step 840172: Output flushed


== Ruins ==


Step 841024: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 843691: Output flushed


Step 843701: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 843986: Output flushed


Step 844313: Output flushed


There are 4 exits:


Step 844393: Output flushed


- north


Step 844491: Output flushed


- south


Step 844577: Output flushed


- east


Step 844653: Output flushed


- west


Step 844729: Output flushed


Step 844782: Output flushed


What do you do?


Step 845150: Output flushed
Step 845181: Input
>>> use blue coin


Step 845310: Output flushed


Step 845311: Output flushed


You place the blue coin into the leftmost open slot.


Step 847490: Output flushed


Step 847568: Output flushed


What do you do?


Step 847936: Output flushed
Step 847967: Input
>>> use red coin


Step 848087: Output flushed


Step 848088: Output flushed


You place the red coin into the leftmost open slot.


Step 850121: Output flushed


Step 850199: Output flushed


What do you do?


Step 850567: Output flushed
Step 850598: Input
>>> use shiny coin


Step 850736: Output flushed


Step 850737: Output flushed


You place the shiny coin into the leftmost open slot.


Step 852882: Output flushed


Step 852960: Output flushed


What do you do?


Step 853328: Output flushed
Step 853359: Input
>>> use concave coin


Step 853515: Output flushed


Step 853516: Output flushed


You place the concave coin into the leftmost open slot.


Step 855743: Output flushed


Step 855821: Output flushed


What do you do?


Step 856189: Output flushed
Step 856220: Input
>>> use corroded coin


Step 856385: Output flushed


Step 856386: Output flushed


You place the corroded coin into the leftmost open slot.


Step 858618: Output flushed


As you place the last coin, you hear a click from the north door.


Step 860193: Output flushed


Step 860264: Output flushed


What do you do?


Step 860632: Output flushed
Step 860663: Input
>>> north


Step 860720: Output flushed


Step 860721: Output flushed


== Ruins ==


Step 861387: Output flushed


Because it has been so well-protected, this room hardly shows signs of decay.  The walls are covered in elaborate murals and decorated with precious metals and stones.


Step 863089: Output flushed


Step 863445: Output flushed


Things of interest here:


Step 864020: Output flushed


- teleporter


Step 864343: Output flushed


Step 864442: Output flushed


There is 1 exit:


Step 864507: Output flushed


- south


Step 864605: Output flushed


Step 864658: Output flushed


What do you do?


Step 865026: Output flushed
Step 865057: Input
>>> take teleporter


Step 865204: Output flushed


Step 865205: Output flushed


Taken.


Step 866454: Output flushed


Step 866520: Output flushed


What do you do?


Step 866888: Output flushed
Step 866919: Input
>>> use teleporter


Step 867057: Output flushed


Step 867058: Output flushed
Step 868128: Getting R7 = 1


A strange, electronic voice is projected into your mind:


Step 869451: Output flushed


Step 869474: Output flushed


  "Unusual setting detected!  Starting confirmation process!  Estimated time to completion: 1 billion years."


Step 872004: Output flushed


Step 872027: Output flushed


In [190]:
c.eip

6042

In [226]:
c.parse_text(6027,50)

6027: op_jt R0 6035
6030: op_add R0 R1 1
6034: op_ret
6035: op_jt R1 6048
6038: op_add R0 R0 -1
6042: op_set R1 R7
6045: op_call 6027
6047: op_ret
6048: op_push R0
6050: op_add R1 R1 -1
6054: op_call 6027
6056: op_set R1 R0
6059: op_pop R0
6061: op_add R0 R0 -1
6065: op_call 6027
6067: op_ret
6068: op_mod 84 101 115
6072: ILLOP 116
6073: ILLOP 32
6074: ILLOP 115
6075: ILLOP 116
6076: ILLOP 114


6027 computes a modified Ackermann function:
```
f(r0, r1) = 
  r1 + 1     if r0 = 0
  f(r0-1,r7) if r1 = 0
  f(r0-1,f(r0,r1-1)) else
 
f(0, x) = x+1
f(1, x) = x+R7+1
f(2, x) = (x+2)*(R7+1) - 1
f(3, x) = ( ((R7+1)**(x+3) - 2R7-1) / R7 ) % MOD
f(4, 1) = f(3, f(4,0)) = f(3, f(3, R7))
```
6027 is called only at 5489 (and recursive calls): `f(4,1)`

In [270]:
[i for i,v in enumerate(c.mem) if v == 6027]

[5490, 6046, 6055, 6066]

In [251]:
def f6027(R7):
    MSK = (1 << 15) - 1
    def powmod(a, b, m):
        r = 1
        while b:
            if b & 1:
                r *= a
                r %= m
            a *= a
            a %= m
            b //= 2
        return r
    def f6027_3(x):
        if R7 == 0: return x+1
        return ((powmod(R7+1,x+3,R7<<15) - 2 * R7 - 1) // R7) % (1 << 15)
    return f6027_3(f6027_3(R7))

In [257]:
f6027s = [f6027(a) for a in range(1 << 15)]

In [258]:
f6027s.count(6), f6027s.index(6)

(1, 25734)

In [272]:
c.parse_text(5491-10,100)

5481: op_noop
5482: op_noop
5483: op_set R0 4
5486: op_set R1 1
5489: op_call 6027
5491: op_eq R1 R0 6
5495: op_jf R1 5579
5498: op_push R0
5500: op_push R1
5502: op_push R2
5504: op_set R0 -3754
5507: op_set R1 1531
5510: op_add R2 10530 2768
5514: op_call 1458
5516: op_pop R2
5518: op_pop R1
5520: op_pop R0
5522: op_set R0 R7
5525: op_set R1 -6902
5528: op_set R2 -1
5531: op_push R3
5533: op_set R3 -3527
5536: op_call 1841
5538: op_pop R3
5540: op_push R0
5542: op_push R1
5544: op_push R2
5546: op_set R0 -3523
5549: op_set R1 1531
5552: op_add R2 6181 963
5556: op_call 1458
5558: op_pop R2
5560: op_pop R1
5562: op_pop R0
5564: op_wmem 2732 2498
5567: op_wmem 2733 0
5570: op_add R1 2708 2
5574: op_wmem R1 -1
5577: op_jmp 5714
5579: op_push R0


In [277]:
# Skip f6027, with the wrong return value
TELEPORT_STEP = 868128
c = computer.Computer()
c.load('challenge.bin')
with open('input.txt') as inp_file:
    c.run(num_steps=TELEPORT_STEP, istream=inp_file)
c.regs[7] = 25734
c.mem[5483] = 1 # op_set
c.mem[5484] = computer.Computer.R0 # R0
c.mem[5485] = 1 # Value
c.mem[5486] = 21 # op_noop
c.mem[5487] = 21 # op_noop
c.mem[5488] = 21 # op_noop
c.mem[5489] = 21 # op_noop
c.mem[5490] = 21 # op_noop
c.run(istream=sys.stdin)

Welcome to the Synacor Challenge!


Step 35: Output flushed


Please record your progress by putting codes like


Step 85: Output flushed


this one into the challenge website: omOdvXeQsntd


Step 135: Output flushed


Step 136: Output flushed


Executing self-test...


Step 159: Output flushed


Step 160: Output flushed
Step 180: Getting R7 = 0


self-test complete, all tests pass


Step 696201: Output flushed


The self-test completion code is: MKwBjhCceLVr


Step 697308: Output flushed


Step 697331: Output flushed


== Foothills ==


Step 697497: Output flushed


You find yourself standing at the base of an enormous mountain.  At its base to the north, there is a massive doorway.  A sign nearby reads "Keep out!  Definitely no treasure within!"


Step 699359: Output flushed


Step 699715: Output flushed


Things of interest here:


Step 700290: Output flushed


- tablet


Step 700423: Output flushed


Step 700672: Output flushed


There are 2 exits:


Step 700744: Output flushed


- doorway


Step 700862: Output flushed


- south


Step 700948: Output flushed


Step 701001: Output flushed


What do you do?


Step 701369: Output flushed
Step 701400: Input
>>> take tablet


Step 701511: Output flushed


Step 701512: Output flushed


Taken.


Step 702358: Output flushed


Step 702424: Output flushed


What do you do?


Step 702792: Output flushed
Step 702823: Input
>>> use tablet


Step 702925: Output flushed


Step 702926: Output flushed


You find yourself writing "SDejwHYBcpaR" on the tablet.  Perhaps it's some kind of code?


Step 706049: Output flushed


Step 706072: Output flushed


Step 706142: Output flushed


What do you do?


Step 706510: Output flushed
Step 706541: Input
>>> doorway


Step 706616: Output flushed


Step 706617: Output flushed


== Dark cave ==


Step 707367: Output flushed


This seems to be the mouth of a deep cave.  As you peer north into the darkness, you think you hear the echoes of bats deeper within.


Step 708729: Output flushed


Step 709056: Output flushed


There are 2 exits:


Step 709128: Output flushed


- north


Step 709226: Output flushed


- south


Step 709312: Output flushed


Step 709365: Output flushed


What do you do?


Step 709733: Output flushed
Step 709764: Input
>>> north


Step 709821: Output flushed


Step 709822: Output flushed


== Dark cave ==


Step 710518: Output flushed


The cave is somewhat narrow here, and the light from the doorway to the south is quite dim.


Step 711460: Output flushed


Step 711787: Output flushed


There are 2 exits:


Step 711859: Output flushed


- north


Step 711957: Output flushed


- south


Step 712043: Output flushed


Step 712096: Output flushed


What do you do?


Step 712464: Output flushed
Step 712495: Input
>>> north


Step 712552: Output flushed


Step 712553: Output flushed


== Dark cave ==


Step 713249: Output flushed


The cave acoustics dramatically change as you find yourself at a legde above a large chasm.  There is barely enough light here to notice a rope bridge leading out into the dark emptiness.


Step 715151: Output flushed


Step 715478: Output flushed


There are 2 exits:


Step 715550: Output flushed


- bridge


Step 715658: Output flushed


- south


Step 715744: Output flushed


Step 715797: Output flushed


What do you do?


Step 716165: Output flushed
Step 716196: Input
>>> bridge


Step 716262: Output flushed


Step 716263: Output flushed


== Rope bridge ==


Step 717006: Output flushed


This rope bridge creaks as you walk along it.  You aren't sure how old it is, or whether it can even support your weight.


Step 718248: Output flushed


Step 718575: Output flushed


There are 2 exits:


Step 718647: Output flushed


- continue


Step 718775: Output flushed


- back


Step 718851: Output flushed


Step 718904: Output flushed


What do you do?


Step 719272: Output flushed
Step 719303: Input
>>> continue


Step 719387: Output flushed


Step 719388: Output flushed


== Falling through the air! ==


Step 720315: Output flushed


As you continue along the bridge, it snaps!  You try to grab the bridge, but it evades your grasp in the darkness.  You are plummeting quickly downward into the chasm...


Step 722037: Output flushed


Step 722364: Output flushed


There is 1 exit:


Step 722429: Output flushed


- down


Step 722517: Output flushed


Step 722570: Output flushed


What do you do?


Step 722938: Output flushed
Step 722969: Input
>>> down


Step 723017: Output flushed


Step 723018: Output flushed


== Moss cavern ==


Step 723879: Output flushed


You are standing in a large cavern full of bioluminescent moss.  It must have broken your fall!  The cavern extends to the east and west; at the west end, you think you see a passage leading out of the cavern.


Step 726001: Output flushed


Step 726328: Output flushed


There are 2 exits:


Step 726400: Output flushed


- west


Step 726488: Output flushed


- east


Step 726564: Output flushed


Step 726617: Output flushed


What do you do?


Step 726985: Output flushed
Step 727016: Input
>>> east


Step 727064: Output flushed


Step 727065: Output flushed


== Moss cavern ==


Step 727977: Output flushed


You are standing in a large cavern full of bioluminescent moss.  The cavern extends to the west.


Step 728969: Output flushed


Step 729325: Output flushed


Things of interest here:


Step 729900: Output flushed


- empty lantern


Step 730118: Output flushed


Step 730352: Output flushed


There is 1 exit:


Step 730417: Output flushed


- west


Step 730505: Output flushed


Step 730558: Output flushed


What do you do?


Step 730926: Output flushed
Step 730957: Input
>>> take empty lantern


Step 731131: Output flushed


Step 731132: Output flushed


Taken.


Step 732120: Output flushed


Step 732186: Output flushed


What do you do?


Step 732554: Output flushed
Step 732585: Input
>>> west


Step 732633: Output flushed


Step 732634: Output flushed


== Moss cavern ==


Step 733479: Output flushed


You are standing in a large cavern full of bioluminescent moss.  It must have broken your fall!  The cavern extends to the east and west; at the west end, you think you see a passage leading out of the cavern.


Step 735601: Output flushed


Step 735928: Output flushed


There are 2 exits:


Step 736000: Output flushed


- west


Step 736088: Output flushed


- east


Step 736164: Output flushed


Step 736217: Output flushed


What do you do?


Step 736585: Output flushed
Step 736616: Input
>>> west


Step 736664: Output flushed


Step 736665: Output flushed


== Moss cavern ==


Step 737510: Output flushed


You are standing in a large cavern full of bioluminescent moss.  The cavern extends to the east.  There is a crevise in the rocks which opens into a passage.


Step 739112: Output flushed


Step 739439: Output flushed


There are 2 exits:


Step 739511: Output flushed


- east


Step 739599: Output flushed


- passage


Step 739705: Output flushed


Step 739758: Output flushed


What do you do?


Step 740126: Output flushed
Step 740157: Input
>>> passage


Step 740232: Output flushed


Step 740233: Output flushed


== Passage ==


Step 740991: Output flushed


You are in a crevise on the west wall of the moss cavern.  A dark passage leads further west.  There is a ladder here which leads down into a smaller, moss-filled cavern below.


Step 742783: Output flushed


Step 743110: Output flushed


There are 3 exits:


Step 743186: Output flushed


- cavern


Step 743294: Output flushed


- ladder


Step 743390: Output flushed


- darkness


Step 743506: Output flushed


Step 743559: Output flushed


What do you do?


Step 743927: Output flushed
Step 743958: Input
>>> ladder


Step 744024: Output flushed


Step 744025: Output flushed


== Twisty passages ==


Step 744878: Output flushed


You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.


Step 746140: Output flushed


Step 746467: Output flushed


There are 5 exits:


Step 746551: Output flushed


- ladder


Step 746659: Output flushed


- north


Step 746745: Output flushed


- south


Step 746831: Output flushed


- east


Step 746907: Output flushed


- west


Step 746983: Output flushed


Step 747036: Output flushed


What do you do?


Step 747404: Output flushed
Step 747435: Input
>>> west


Step 747483: Output flushed


Step 747484: Output flushed


== Twisty passages ==


Step 748532: Output flushed


You are in a little maze of twisty passages, all alike.


Step 749114: Output flushed


Step 749441: Output flushed


There are 3 exits:


Step 749517: Output flushed


- north


Step 749615: Output flushed


- south


Step 749701: Output flushed


- east


Step 749777: Output flushed


Step 749830: Output flushed


What do you do?


Step 750198: Output flushed
Step 750229: Input
>>> south


Step 750286: Output flushed


Step 750287: Output flushed


== Twisty passages ==


Step 751122: Output flushed


You are in a twisty alike of little passages, all maze.


Step 751699: Output flushed


Step 751709: Output flushed


The east passage appears very dark; you feel likely to be eaten by a Grue.


Step 752464: Output flushed


Step 752791: Output flushed


There are 4 exits:


Step 752871: Output flushed


- north


Step 752969: Output flushed


- south


Step 753055: Output flushed


- west


Step 753131: Output flushed


- east


Step 753207: Output flushed


Step 753260: Output flushed


What do you do?


Step 753628: Output flushed
Step 753659: Input
>>> north


Step 753716: Output flushed


Step 753717: Output flushed


Chiseled on the wall of one of the passageways, you see:


Step 755612: Output flushed


Step 755635: Output flushed


    aiEbrVscqNRb


Step 756423: Output flushed


Step 756446: Output flushed


You take note of this and keep walking.


Step 757366: Output flushed


Step 757389: Output flushed


== Twisty passages ==


Step 757608: Output flushed


You are in a maze of twisty little passages, all alike.


Step 758190: Output flushed


Step 758546: Output flushed


Things of interest here:


Step 759121: Output flushed


- can


Step 759284: Output flushed


Step 759473: Output flushed


There is 1 exit:


Step 759538: Output flushed


- west


Step 759626: Output flushed


Step 759679: Output flushed


What do you do?


Step 760047: Output flushed
Step 760078: Input
>>> take can


Step 760162: Output flushed


Step 760163: Output flushed


Taken.


Step 761081: Output flushed


Step 761147: Output flushed


What do you do?


Step 761515: Output flushed
Step 761546: Input
>>> use can


Step 761621: Output flushed


Step 761622: Output flushed


You fill your lantern with oil.  It seems to cheer up!


Step 763644: Output flushed


Step 763667: Output flushed


Step 763735: Output flushed


What do you do?


Step 764103: Output flushed
Step 764134: Input
>>> use lantern


Step 764245: Output flushed


Step 764246: Output flushed


You light your lantern.


Step 765554: Output flushed


Step 765577: Output flushed


== Twisty passages ==


Step 765806: Output flushed


You are in a maze of twisty little passages, all alike.


Step 766388: Output flushed


Step 766715: Output flushed


There is 1 exit:


Step 766780: Output flushed


- west


Step 766868: Output flushed


Step 766921: Output flushed


What do you do?


Step 767289: Output flushed
Step 767320: Input
>>> west


Step 767368: Output flushed


Step 767369: Output flushed


== Twisty passages ==


Step 768257: Output flushed


You are in a maze of twisty little passages, all dimly lit by more bioluminescent moss.  There is a ladder here leading up.


Step 769519: Output flushed


Step 769846: Output flushed


There are 5 exits:


Step 769930: Output flushed


- ladder


Step 770038: Output flushed


- north


Step 770124: Output flushed


- south


Step 770210: Output flushed


- east


Step 770286: Output flushed


- west


Step 770362: Output flushed


Step 770415: Output flushed


What do you do?


Step 770783: Output flushed
Step 770814: Input
>>> ladder


Step 770880: Output flushed


Step 770881: Output flushed


== Passage ==


Step 771584: Output flushed


You are in a crevise on the west wall of the moss cavern.  A dark passage leads further west.  There is a ladder here which leads down into a smaller, moss-filled cavern below.


Step 773376: Output flushed


Step 773703: Output flushed


There are 3 exits:


Step 773779: Output flushed


- cavern


Step 773887: Output flushed


- ladder


Step 773983: Output flushed


- darkness


Step 774099: Output flushed


Step 774152: Output flushed


What do you do?


Step 774520: Output flushed
Step 774551: Input
>>> darkness


Step 774635: Output flushed


Step 774636: Output flushed


== Passage ==


Step 775449: Output flushed


You feel that your light source is more than sufficient to keep grues away.


Step 776248: Output flushed


Step 776575: Output flushed


There are 2 exits:


Step 776647: Output flushed


- continue


Step 776775: Output flushed


- back


Step 776851: Output flushed


Step 776904: Output flushed


What do you do?


Step 777272: Output flushed
Step 777303: Input
>>> continue


Step 777387: Output flushed


Step 777388: Output flushed


== Dark passage ==


Step 778215: Output flushed


You are in a narrow passage.  There is darkness to the west, but you can barely see a glowing opening to the east.


Step 779387: Output flushed


Step 779714: Output flushed


There are 2 exits:


Step 779786: Output flushed


- west


Step 779874: Output flushed


- east


Step 779950: Output flushed


Step 780003: Output flushed


What do you do?


Step 780371: Output flushed
Step 780402: Input
>>> west


Step 780450: Output flushed


Step 780451: Output flushed


== Dark passage ==


Step 781326: Output flushed


You are in a dark, narrow passage.


Step 781698: Output flushed


Step 782025: Output flushed


There are 2 exits:


Step 782097: Output flushed


- east


Step 782185: Output flushed


- west


Step 782261: Output flushed


Step 782314: Output flushed


What do you do?


Step 782682: Output flushed
Step 782713: Input
>>> west


Step 782761: Output flushed


Step 782762: Output flushed


== Dark passage ==


Step 783704: Output flushed


You are in a dark, narrow passage.


Step 784076: Output flushed


Step 784403: Output flushed


There are 2 exits:


Step 784475: Output flushed


- east


Step 784563: Output flushed


- west


Step 784639: Output flushed


Step 784692: Output flushed


What do you do?


Step 785060: Output flushed
Step 785091: Input
>>> west


Step 785139: Output flushed


Step 785140: Output flushed


== Dark passage ==


Step 786082: Output flushed


You are in a dark, narrow passage.  To the west, you spot some vegetation where the passage expands.


Step 787114: Output flushed


Step 787441: Output flushed


There are 2 exits:


Step 787513: Output flushed


- east


Step 787601: Output flushed


- west


Step 787677: Output flushed


Step 787730: Output flushed


What do you do?


Step 788098: Output flushed
Step 788129: Input
>>> west


Step 788177: Output flushed


Step 788178: Output flushed


== Ruins ==


Step 789030: Output flushed


You stand in a large cavern with a huge ruin to the north, overgrown by plant life.  There is a large stone archway to the north acting as the doorway to the ruined complex.  A crevice in the rock to the east leads to an alarmingly dark passageway.


Step 791542: Output flushed


Step 791869: Output flushed


There are 2 exits:


Step 791941: Output flushed


- east


Step 792029: Output flushed


- north


Step 792115: Output flushed


Step 792168: Output flushed


What do you do?


Step 792536: Output flushed
Step 792567: Input
>>> north


Step 792624: Output flushed


Step 792625: Output flushed


== Ruins ==


Step 793309: Output flushed


You are in the once-opulent foyer of a massive ruined complex.  There is a door to the south leading to the overgrowth outside and stairs to the north which lead into a larger hall.


Step 795151: Output flushed


Step 795507: Output flushed


Things of interest here:


Step 796082: Output flushed


- red coin


Step 796310: Output flushed


Step 796484: Output flushed


There are 2 exits:


Step 796556: Output flushed


- north


Step 796654: Output flushed


- south


Step 796740: Output flushed


Step 796793: Output flushed


What do you do?


Step 797161: Output flushed
Step 797192: Input
>>> take red coin


Step 797321: Output flushed


Step 797322: Output flushed


Taken.


Step 798350: Output flushed


Step 798416: Output flushed


What do you do?


Step 798784: Output flushed
Step 798815: Input
>>> north


Step 798872: Output flushed


Step 798873: Output flushed


== Ruins ==


Step 799529: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 802196: Output flushed


Step 802206: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 802491: Output flushed


Step 802818: Output flushed


There are 4 exits:


Step 802898: Output flushed


- north


Step 802996: Output flushed


- south


Step 803082: Output flushed


- east


Step 803158: Output flushed


- west


Step 803234: Output flushed


Step 803287: Output flushed


What do you do?


Step 803655: Output flushed
Step 803686: Input
>>> west


Step 803734: Output flushed


Step 803735: Output flushed


== Ruins ==


Step 804643: Output flushed


You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.


Step 806465: Output flushed


Step 806821: Output flushed


Things of interest here:


Step 807396: Output flushed


- blue coin


Step 807694: Output flushed


Step 807808: Output flushed


There are 2 exits:


Step 807880: Output flushed


- up


Step 807948: Output flushed


- east


Step 808024: Output flushed


Step 808077: Output flushed


What do you do?


Step 808445: Output flushed
Step 808476: Input
>>> take blue coin


Step 808614: Output flushed


Step 808615: Output flushed


Taken.


Step 809779: Output flushed


Step 809845: Output flushed


What do you do?


Step 810213: Output flushed
Step 810244: Input
>>> up


Step 810274: Output flushed


Step 810275: Output flushed


== Ruins ==


Step 810889: Output flushed


This was long ago a lavish throne room.  Dried-up fountains and crumbling statues line the walls, and the carved stone throne in the center of the room is falling apart.


Step 812611: Output flushed


Step 812967: Output flushed


Things of interest here:


Step 813542: Output flushed


- shiny coin


Step 813820: Output flushed


Step 813964: Output flushed


There is 1 exit:


Step 814029: Output flushed


- down


Step 814117: Output flushed


Step 814170: Output flushed


What do you do?


Step 814538: Output flushed
Step 814569: Input
>>> take shiny coin


Step 814716: Output flushed


Step 814717: Output flushed


Taken.


Step 815837: Output flushed


Step 815903: Output flushed


What do you do?


Step 816271: Output flushed
Step 816302: Input
>>> down


Step 816350: Output flushed


Step 816351: Output flushed


== Ruins ==


Step 817152: Output flushed


You find yourself in what was once the living quarters for the complex.  Many smaller rooms which once had walls to divide them now lay in disarray.  There is a staircase up here.


Step 818974: Output flushed


Step 819301: Output flushed


There are 2 exits:


Step 819373: Output flushed


- up


Step 819441: Output flushed


- east


Step 819517: Output flushed


Step 819570: Output flushed


What do you do?


Step 819938: Output flushed
Step 819969: Input
>>> east


Step 820017: Output flushed


Step 820018: Output flushed


== Ruins ==


Step 820831: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 823498: Output flushed


Step 823508: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 823793: Output flushed


Step 824120: Output flushed


There are 4 exits:


Step 824200: Output flushed


- north


Step 824298: Output flushed


- south


Step 824384: Output flushed


- east


Step 824460: Output flushed


- west


Step 824536: Output flushed


Step 824589: Output flushed


What do you do?


Step 824957: Output flushed
Step 824988: Input
>>> east


Step 825036: Output flushed


Step 825037: Output flushed


== Ruins ==


Step 825878: Output flushed


You stand in what seems to have once been a dining hall; broken tables and pottery are scattered everywhere.  A staircase here leads down.


Step 827290: Output flushed


Step 827646: Output flushed


Things of interest here:


Step 828221: Output flushed


- concave coin


Step 828534: Output flushed


Step 828663: Output flushed


There are 2 exits:


Step 828735: Output flushed


- down


Step 828823: Output flushed


- west


Step 828899: Output flushed


Step 828952: Output flushed


What do you do?


Step 829320: Output flushed
Step 829351: Input
>>> take concave coin


Step 829516: Output flushed


Step 829517: Output flushed


Taken.


Step 830699: Output flushed


Step 830765: Output flushed


What do you do?


Step 831133: Output flushed
Step 831164: Input
>>> down


Step 831212: Output flushed


Step 831213: Output flushed


== Ruins ==


Step 832014: Output flushed


This seems to be a kitchen; there are brick stoves and shelves along the wall.  Everything here has fallen into disrepair.


Step 833266: Output flushed


Step 833622: Output flushed


Things of interest here:


Step 834197: Output flushed


- corroded coin


Step 834490: Output flushed


Step 834649: Output flushed


There is 1 exit:


Step 834714: Output flushed


- up


Step 834782: Output flushed


Step 834835: Output flushed


What do you do?


Step 835203: Output flushed
Step 835234: Input
>>> take corroded coin


Step 835408: Output flushed


Step 835409: Output flushed


Taken.


Step 836586: Output flushed


Step 836652: Output flushed


What do you do?


Step 837020: Output flushed
Step 837051: Input
>>> up


Step 837081: Output flushed


Step 837082: Output flushed


== Ruins ==


Step 837696: Output flushed


You stand in what seems to have once been a dining hall; broken tables and pottery are scattered everywhere.  A staircase here leads down.


Step 839108: Output flushed


Step 839435: Output flushed


There are 2 exits:


Step 839507: Output flushed


- down


Step 839595: Output flushed


- west


Step 839671: Output flushed


Step 839724: Output flushed


What do you do?


Step 840092: Output flushed
Step 840123: Input
>>> west


Step 840171: Output flushed


Step 840172: Output flushed


== Ruins ==


Step 841024: Output flushed


You stand in the massive central hall of these ruins.  The walls are crumbling, and vegetation has clearly taken over.  Rooms are attached in all directions.  There is a strange monument in the center of the hall with circular slots and unusual symbols.  It reads:


Step 843691: Output flushed


Step 843701: Output flushed


_ + _ * _^2 + _^3 - _ = 399


Step 843986: Output flushed


Step 844313: Output flushed


There are 4 exits:


Step 844393: Output flushed


- north


Step 844491: Output flushed


- south


Step 844577: Output flushed


- east


Step 844653: Output flushed


- west


Step 844729: Output flushed


Step 844782: Output flushed


What do you do?


Step 845150: Output flushed
Step 845181: Input
>>> use blue coin


Step 845310: Output flushed


Step 845311: Output flushed


You place the blue coin into the leftmost open slot.


Step 847490: Output flushed


Step 847568: Output flushed


What do you do?


Step 847936: Output flushed
Step 847967: Input
>>> use red coin


Step 848087: Output flushed


Step 848088: Output flushed


You place the red coin into the leftmost open slot.


Step 850121: Output flushed


Step 850199: Output flushed


What do you do?


Step 850567: Output flushed
Step 850598: Input
>>> use shiny coin


Step 850736: Output flushed


Step 850737: Output flushed


You place the shiny coin into the leftmost open slot.


Step 852882: Output flushed


Step 852960: Output flushed


What do you do?


Step 853328: Output flushed
Step 853359: Input
>>> use concave coin


Step 853515: Output flushed


Step 853516: Output flushed


You place the concave coin into the leftmost open slot.


Step 855743: Output flushed


Step 855821: Output flushed


What do you do?


Step 856189: Output flushed
Step 856220: Input
>>> use corroded coin


Step 856385: Output flushed


Step 856386: Output flushed


You place the corroded coin into the leftmost open slot.


Step 858618: Output flushed


As you place the last coin, you hear a click from the north door.


Step 860193: Output flushed


Step 860264: Output flushed


What do you do?


Step 860632: Output flushed
Step 860663: Input
>>> north


Step 860720: Output flushed


Step 860721: Output flushed


== Ruins ==


Step 861387: Output flushed


Because it has been so well-protected, this room hardly shows signs of decay.  The walls are covered in elaborate murals and decorated with precious metals and stones.


Step 863089: Output flushed


Step 863445: Output flushed


Things of interest here:


Step 864020: Output flushed


- teleporter


Step 864343: Output flushed


Step 864442: Output flushed


There is 1 exit:


Step 864507: Output flushed


- south


Step 864605: Output flushed


Step 864658: Output flushed


What do you do?


Step 865026: Output flushed
Step 865057: Input
>>> take teleporter


Step 865204: Output flushed


Step 865205: Output flushed


Taken.


Step 866454: Output flushed


Step 866520: Output flushed


What do you do?


Step 866888: Output flushed
Step 866919: Input
>>> use teleporter


Step 867057: Output flushed


Step 867058: Output flushed
Step 868128: Getting R7 = 25734


A strange, electronic voice is projected into your mind:


Step 869451: Output flushed


Step 869474: Output flushed


  "Unusual setting detected!  Starting confirmation process!  Estimated time to completion: 1 billion years."


Step 872004: Output flushed


Step 872027: Output flushed


A strange, electronic voice is projected into your mind:


Step 873379: Output flushed


Step 873402: Output flushed


  "Miscalibration detected!  Aborting teleportation!"


Step 874644: Output flushed


Step 874667: Output flushed


Nothing else seems to happen.


Step 875357: Output flushed


Step 875380: Output flushed


Step 875450: Output flushed


What do you do?


Step 875818: Output flushed
Step 875849: Input


KeyboardInterrupt: 

In [279]:
# Skip f6027, with the right return value
TELEPORT_STEP = 868128
c = computer.Computer()
c.load('challenge.bin')
with open('input.txt') as inp_file:
    c.run(num_steps=TELEPORT_STEP, istream=inp_file)
c.regs[7] = 25734
c.mem[5483] = 1 # op_set
c.mem[5484] = computer.Computer.R0 # R0
c.mem[5485] = 6 # Value
c.mem[5486] = 21 # op_noop
c.mem[5487] = 21 # op_noop
c.mem[5488] = 21 # op_noop
c.mem[5489] = 21 # op_noop
c.mem[5490] = 21 # op_noop
c.run(istream=sys.stdin)

Welcome to the Synacor Challenge!


TypeError: 'bool' object is not callable

In [227]:
c.parse_text(5579,50)

5579: op_push R0
5581: op_push R1
5583: op_push R2
5585: op_set R0 -3368
5588: op_set R1 1531
5591: op_add R2 15134 3037
5595: op_call 1458
5597: op_pop R2
5599: op_pop R1
5601: op_pop R0
5603: op_jmp 5714
5605: op_push R0
5607: op_push R1
5609: op_push R2
5611: op_set R0 -3223
5614: op_set R1 1531
5617: op_add R2 325 156
5621: op_call 1458
5623: op_pop R2
5625: op_pop R1
5627: op_pop R0


In [271]:
c.parse_text(1531, 80)

1531: op_push R1
1533: op_set R1 R2
1536: op_call 2125
1538: op_out R0
1540: op_pop R1
1542: op_ret
1543: op_push R1
1545: op_push R3
1547: op_rmem R3 R0
1550: op_jf R3 1563
1553: op_call 1458
1555: op_jt R1 1563
1558: op_set R0 R2
1561: op_jmp 1566
1563: op_set R0 -1
1566: op_pop R3
1568: op_pop R1
1570: op_ret
1571: op_push R1
1573: op_push R2
1575: op_set R2 R1
1578: op_set R1 1605
1581: op_call 1543
1583: op_pop R2
1585: op_pop R1
1587: op_ret
1588: op_push R1
1590: op_push R2
1592: op_set R2 R1
1595: op_set R1 1648
1598: op_call 1543
1600: op_pop R2
1602: op_pop R1
1604: op_ret
1605: op_eq R0 R0 R2
1609: op_jf R0 1618


In [265]:
c.parse_text(1458,80)

1458: op_push R0
1460: op_push R3
1462: op_push R4
1464: op_push R5
1466: op_push R6
1468: op_set R6 R0
1471: op_set R5 R1
1474: op_rmem R4 R0
1477: op_set R1 0
1480: op_add R3 1 R1
1484: op_gt R0 R3 R4
1488: op_jt R0 1507
1491: op_add R3 R3 R6
1495: op_rmem R0 R3
1498: op_call R5
1500: op_add R1 R1 1
1504: op_jt R1 1480
1507: op_pop R6
1509: op_pop R5
1511: op_pop R4
1513: op_pop R3
1515: op_pop R0
1517: op_ret
1518: op_push R1
1520: op_set R1 1528
1523: op_call 1458
1525: op_pop R1
1527: op_ret
1528: op_out R0
1530: op_ret
1531: op_push R1
1533: op_set R1 R2
1536: op_call 2125


In [192]:
c.stack

[6080, 16, 6124, 1, 2952, 25978, 3568, 3599, 2708, 5445, 3, 5491, 4, 6056]

In [258]:
f6027s.count(6), f6027s.index(6)

(1, 25734)

In [226]:
c.parse_text(6027,50)

6027: op_jt R0 6035
6030: op_add R0 R1 1
6034: op_ret
6035: op_jt R1 6048
6038: op_add R0 R0 -1
6042: op_set R1 R7
6045: op_call 6027
6047: op_ret
6048: op_push R0
6050: op_add R1 R1 -1
6054: op_call 6027
6056: op_set R1 R0
6059: op_pop R0
6061: op_add R0 R0 -1
6065: op_call 6027
6067: op_ret
6068: op_mod 84 101 115
6072: ILLOP 116
6073: ILLOP 32
6074: ILLOP 115
6075: ILLOP 116
6076: ILLOP 114


6027 computes a modified Ackermann function:
```
f(r0, r1) = 
  r1 + 1     if r0 = 0
  f(r0-1,r7) if r1 = 0
  f(r0-1,f(r0,r1-1)) else
 
f(0, x) = x+1
f(1, x) = x+R7+1
f(2, x) = (x+2)*(R7+1) - 1
f(3, x) = ( ((R7+1)**(x+3) - 2R7-1) / R7 ) % MOD
f(4, 1) = f(3, f(4,0)) = f(3, f(3, R7))
```
6027 is called only at 5489 (and recursive calls): `f(4,1)`

In [270]:
[i for i,v in enumerate(c.mem) if v == 6027]

[5490, 6046, 6055, 6066]

In [251]:
def f6027(R7):
    MSK = (1 << 15) - 1
    def powmod(a, b, m):
        r = 1
        while b:
            if b & 1:
                r *= a
                r %= m
            a *= a
            a %= m
            b //= 2
        return r
    def f6027_3(x):
        if R7 == 0: return x+1
        return ((powmod(R7+1,x+3,R7<<15) - 2 * R7 - 1) // R7) % (1 << 15)
    return f6027_3(f6027_3(R7))

In [257]:
f6027s = [f6027(a) for a in range(1 << 15)]